### ISSUE TITLE
How to debug stratum_bmv2 

### ISSUE THREAD

**Issue by drobinkent** [stratum/stratum#108]
I am using the bmv2 as p4 switch simulator. I have followed the steps described here https://github.com/stratum/stratum/blob/master/stratum/hal/bin/bmv2/README.md .

Whenever I try to debug a bmv2 switch (running as mininet switch) using eclipse it never succeeds. I have used Eclipse IDE. Threads of the bmv2 switch can be seen in Eclipse. But I can not actually debug the bmv2 codes. I tried to attach the stratum_bmv2 binary as remote process to be debugged in eclipse.

Seems I am missing something. Is there any other way to debug the bmv2?  Or any other better way can be used to debug it?

**Comment by Yi-Tseng** [comment]
If you want to include debug symbol to the binary, you can add this flag:
`--compilation_mode=dbg`

Ref: https://stackoverflow.com/questions/45812725/c-debugging-with-gdb-bazel-emacs

**Comment by drobinkent** [comment]
thanks.
