### ISSUE TITLE
what bazel version should i use to build the stratum

### ISSUE THREAD

**Issue by Colaplusice** [stratum/stratum#121]
**Describe the bug**
I met different kinds of errors when I have tried use different bazel version to build  stratum for tofino SDE.
**Environment**
Help us understand by giving us some context of your setup.
when I use bazel 2.0 , the error is :
```
ERROR: /home/ubuntu/asterfusion/stratum/stratum/hal/bin/barefoot/BUILD:24:1: file '//bazel:rules.bzl' does not contain symbol 'stratum_cc_binary'
ERROR: Skipping '//stratum/hal/bin/barefoot:stratum_bf': no such target '//stratum/hal/bin/barefoot:stratum_bf': target 'stratum_bf' not declared in package 'stratum/hal/bin/barefoot' defined by /home/ubuntu/asterfusion/stratum/stratum/hal/bin/barefoot/BUILD
WARNING: Target pattern parsing failed.
ERROR: no such target '//stratum/hal/bin/barefoot:stratum_bf': target 'stratum_bf' not declared in package 'stratum/hal/bin/barefoot' defined by /home/ubuntu/asterfusion/stratum/stratum/hal/bin/barefoot/BUILD
```
when i use bazel 0.20 ，the error is 
```
ERROR: error loading package '': in /home/ubuntu/.cache/bazel/_bazel_ubuntu/69559fb472981a06aaa6cb6210fe0eb9/external/com_github_grpc_grpc/bazel/grpc_python_deps.bzl: Encountered error while reading extension file 'requirements.bzl': no such package '@grpc_python_dependencies//': pip_import failed: Collecting coverage>=4.0 (from -r /home/ubuntu/.cache/bazel/_bazel_ubuntu/69559fb472981a06aaa6cb6210fe0eb9/external/com_github_grpc_grpc/requirements.bazel.txt (line 2))
 (  Could not find a version that satisfies the requirement coverage>=4.0 (from -r /home/ubuntu/.cache/bazel/_bazel_ubuntu/69559fb472981a06aaa6cb6210fe0eb9/external/com_github_grpc_grpc/requirements.bazel.txt (line 2)) (from versions: )
No matching distribution found for coverage>=4.0 (from -r /home/ubuntu/.cache/bazel/_bazel_ubuntu/69559fb472981a06aaa6cb6210fe0eb9/external/com_github_grpc_grpc/requirements.bazel.txt (line 2))
)
ERROR: error loading package '': in /home/ubuntu/.cache/bazel/_bazel_ubuntu/69559fb472981a06aaa6cb6210fe0eb9/external/com_github_grpc_grpc/bazel/grpc_python_deps.bzl: Encountered error while reading extension file 'requirements.bzl': no such package '@grpc_python_dependencies//': pip_import failed: Collecting coverage>=4.0 (from -r /home/ubuntu/.cache/bazel/_bazel_ubuntu/69559fb472981a06aaa6cb6210fe0eb9/external/com_github_grpc_grpc/requirements.bazel.txt (line 2))
 (  Could not find a version that satisfies the requirement coverage>=4.0 (from -r /home/ubuntu/.cache/bazel/_bazel_ubuntu/69559fb472981a06aaa6cb6210fe0eb9/external/com_github_grpc_grpc/requirements.bazel.txt (line 2)) (from versions: )
No matching distribution found for coverage>=4.0 (from -r /home/ubuntu/.cache/bazel/_bazel_ubuntu/69559fb472981a06aaa6cb6210fe0eb9/external/com_github_grpc_grpc/requirements.bazel.txt (line 2))
)
```

If building from source:
`bazel version`
2.0.0
0.20.0

Switch:
```bash
tofine 
SDE-9.0.0
```

**To Reproduce**
1. Use this config '....'
2. Run this command '....'
3. See error

**Expected behavior**

**Additional context**

**Comment by pudelkoM** [comment]
0.23.2

**Comment by Colaplusice** [comment]
> 0.23.2

Thanks for your reply. But I am strucked by this problem for a while : 
![image](https://user-images.githubusercontent.com/29660460/74547586-4ed54380-4f87-11ea-9110-41edb470a879.png)
Have you ever met this problem?

**Comment by Yi-Tseng** [comment]
> > 0.23.2
> 
> Thanks for your reply. But I am strucked by this problem for a while :
> ![image](https://user-images.githubusercontent.com/29660460/74547586-4ed54380-4f87-11ea-9110-41edb470a879.png)
> Have you ever met this problem?

The reason this happened is that the PI library in the container does not match the library required by Barefoot SDE.
Did you install libraries required by Barefoot SDE into the container?

**Comment by Yi-Tseng** [comment]
We moved to Bazel 2.2.0 a few days ago. 

let me know if there still an issue.

**Comment by Yi-Tseng** [comment]
> > 0.23.2
> 
> Thanks for your reply. But I am strucked by this problem for a while :
> ![image](https://user-images.githubusercontent.com/29660460/74547586-4ed54380-4f87-11ea-9110-41edb470a879.png)
> Have you ever met this problem?

Did you use the p4 studio tool to build the SDE? Are you using the Stratum profile?
