### ISSUE TITLE
 Create a Stratum container image without kernel module

### ISSUE THREAD

**Issue by Yi-Tseng** [stratum/stratum#140]
Some devices use different Linux-based system with different Kernel (e.g. 4.x generic)

Currently, we put kernel module file (.ko) to the container and loads the kernel module when we run the entry point script.

To make Stratum works with different Kernel, we can load the custom kernel module before we start the container and starts the Stratum directly in the container without loading the kernel module.

**Comment by devalb** [comment]
Thanks Yi, looking forward to it.
