### ISSUE TITLE
 Assertion `abi_version == PI_ABI_VERSION && "PI ABI version mismatch"' failed.

### ISSUE THREAD

**Issue by lxlmummy** [stratum/stratum#160]
when I compile ok in the docker，I run the stratum bmv2 like flow:
jamescook@b5a76e3f9ab7:/stratum$ ./bazel-bin/stratum/hal/bin/bmv2/stratum_bmv2 --external_stratum_urls=0.0.0.0:28000 --persistent_config_dir=./tmp --chassis_config_file=./tmp/chassis_config.pb.txt --bmv2_log_level=debug
stratum_bmv2: external/com_github_p4lang_PI/src/pi.c:159: pi_init: Assertion `abi_version == PI_ABI_VERSION && "PI ABI version mismatch"' failed.
*** Aborted at 1583478535 (unix time) try "date -d @1583478535" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x3e800007923) received by PID 31011 (TID 0x7f101c6c6f00) from PID 31011; stack trace: ***
    @     0x7f101b57f0e0 (unknown)
    @     0x7f101afeafff gsignal
    @     0x7f101afec42a abort
    @     0x7f101afe3e67 (unknown)
    @     0x7f101afe3f12 __assert_fail
    @     0x55c446e60e07 pi_init
    @     0x55c446d4822f pi::fe::proto::DeviceMgrImp::init()
    @     0x55c446d3b2a4 pi::fe::proto::DeviceMgr::init()
    @     0x55c446625db5 stratum::hal::bmv2::Main()
    @     0x55c4466267e9 main
    @     0x7f101afd82e1 __libc_start_main
    @     0x55c446624faa _start
    @                0x0 (unknown)
Aborted (core dumped)

is this a bug？or my input error？

chassis_config.pb.txt  contents  as follow: 
jamescook@b5a76e3f9ab7:/stratum$ cat tmp/chassis_config.pb.txt 
description: "Default Chassis Config, which does not instantiate any port"
chassis {
  platform: PLT_BAREFOOT_TOFINO
  name: "tofino"
}
nodes {
  id: 1
  slot: 1
  index: 1
}jamescook@b5a76e3f9ab7:/stratum$ 

how can I solve this problem?

**Comment by Yi-Tseng** [comment]
Can you verify that your base build image is the newest one?

```
docker pull stratumproject/build:build
build: Pulling from stratumproject/build
Digest: sha256:1ee3d319ab0b56b78bdb3d46cbfa005a414578a2e5ebe9763234d8c94a8f01cb
Status: Image is up to date for stratumproject/build:build
docker.io/stratumproject/build:build
```

**Comment by lxlmummy** [comment]
@Yi-Tseng , my image info，It is the newest one，as follow：
jamescook@jamescook-VirtualBox:~$ docker pull stratumproject/build:build
build: Pulling from stratumproject/build
Digest: sha256:1ee3d319ab0b56b78bdb3d46cbfa005a414578a2e5ebe9763234d8c94a8f01cb
Status: Image is up to date for stratumproject/build:build
jamescook@jamescook-VirtualBox:~$

**Comment by Yi-Tseng** [comment]
I think the build system uses the old cache to build Stratum. Can you try `bazel clean --expunge` and build it again?

**Comment by lxlmummy** [comment]
@Yi-Tseng , I had tried before I make this issue，bazel clean --expunge and rebuild did not work 。

**Comment by stolsma** [comment]
Are you sure you compile for a barefoot tofino? As in your initial comment the log is stating:

jamescook@b5a76e3f9ab7:/stratum$ ./bazel-bin/stratum/hal/bin/bmv2/stratum_bmv2 --external_stratum_urls=0.0.0.0:28000 --persistent_config_dir=./tmp --chassis_config_file=./tmp/chassis_config.pb.txt --bmv2_log_level=debug

My conclusion from this line is that you start the bmv2 version of stratum and as such the startup will crash because the hardware is not compatible...

**Comment by lxlmummy** [comment]
@stolsma ,  I am not buid for barefoot，but for bmv2 according to flow link：
https://github.com/stratum/stratum/blob/master/stratum/hal/bin/bmv2/README.md
why you say I compile for a barefoot tofino？ if so，How can I do correck？

**Comment by lxlmummy** [comment]
@stolsma ，I see，I use the wrong chassis_config.pb.txt， It was for PLT_BAREFOOT_TOFINO。I will retry，thanks very much,

**Comment by lxlmummy** [comment]
@stolsma , I have use the bmv chassis_config.pb.txt，but it also coredump，follow is info:

root@jamescook-VirtualBox:/home/jamescook/lab/stratum/tmp# ../stratum-master/bazel-bin/stratum/hal/bin/bmv2/stratum_bmv2 --external_stratum_urls=0.0.0.0:28000 --persistent_config_dir=/home/jamescook/lab/stratum/tmp --chassis_config_file=/home/jamescook/lab/stratum/tmp/sample_config.proto.txt --bmv2_log_level=debug
stratum_bmv2: external/com_github_p4lang_PI/src/pi.c:159: pi_init: Assertion `abi_version == PI_ABI_VERSION && "PI ABI version mismatch"' failed.
*** Aborted at 1583893587 (unix time) try "date -d @1583893587" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x9ec) received by PID 2540 (TID 0x7f83b4cb9f40) from PID 2540; stack trace: ***
    @     0x7f83b41fe890 (unknown)
    @     0x7f83b34fae97 gsignal
    @     0x7f83b34fc801 abort
    @     0x7f83b34ec39a (unknown)
    @     0x7f83b34ec412 __assert_fail
    @     0x559899082469 pi_init
    @     0x559898f71ff9 pi::fe::proto::DeviceMgrImp::init()
    @     0x559898f6542a pi::fe::proto::DeviceMgr::init()
    @     0x5598988a724f stratum::hal::bmv2::Main()
    @     0x5598988a7c86 main
    @     0x7f83b34ddb97 __libc_start_main
    @     0x5598988a646a _start
    @                0x0 (unknown)
Aborted (core dumped)
root@jamescook-VirtualBox:/home/jamescook/lab/stratum/tmp# cat /home/jamescook/lab/stratum/tmp/sample_config.proto.txt
description: "Sample config"
chassis {
  platform: PLT_P4_SOFT_SWITCH
  name: "bmv2-simple_switch"
}
nodes {
  id: 1
  slot: 1
  index: 1
}
singleton_ports {
  id: 1
  name: "veth0"
  slot: 1
  port: 1
  channel: 1
  speed_bps: 100000000000
  config_params {
    admin_state: ADMIN_STATE_ENABLED
  }
  node: 1
}
singleton_ports {
  id: 2
  name: "veth2"
  slot: 1
  port: 2
  channel: 1
  speed_bps: 100000000000
  config_params {
    admin_state: ADMIN_STATE_ENABLED
  }
  node: 1
}
root@jamescook-VirtualBox:/home/jamescook/lab/stratum/tmp#

**Comment by lxlmummy** [comment]
I find the problem, I git clone https://github.com/p4lang/PI.git，default use the master branch to build，but PI project do not allow user to use master，the PI_ABI_VERSION in the pi.h is 2. Use another PI branch or change PI_ABI_VERSION to 1 by hand，the result is OK.

**Comment by nonylene** [comment]
I had the same issue on Wedge100BF, SDE 9.1.1. This was caused from `PI_ABI_VERESION` of `PI` stratum using is 2 while P4 studio in SDE 9.1.1 uses `PI` which `PI_ABI_VERSION` is 1.

I have resolved this problem by adding the corresponding `PI` revision for SDE 9.1.1 ( `9_1_1` ) to bazel deps.

https://github.com/stratum/stratum/blob/a0b39ae472a72c0bcefd341011cc9df7dea8b368/bazel/deps.bzl#L22-L27
