### ISSUE TITLE
Failed to build Stratum

### ISSUE THREAD

**Issue by Muthuramane** [stratum/stratum#161]
**Describe the bug**
I synced master stratum repository code, and I couldn't make a build.

**Environment**
x86-64-accton-wedge100bf-65x-r0

If building from source:
$ bazel version
Build label: 0.23.2
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Mar 11 16:47:03 2019 (1552322823)
Build timestamp: 1552322823
Build timestamp as int: 1552322823

Switch:
$cat /etc/onl/platform
x86-64-accton-wedge100bf-65x-r0

$uname -a
Linux localhost 4.14.49-OpenNetworkLinux #1 SMP Sat May 4 16:37:07 UTC 2019 x86_64 GNU/Linux

$lsmod
Module                  Size  Used by
bf_kdrv                28672  0 
x86_pkg_temp_thermal    16384  0 
gpio_ich               16384  0 
optoe                  20480  0 

**To Reproduce**
1. Use this config:
    ./p4studio_build.py -up profiles/stratum_profile.yaml --bsp-path $BSP_PATH 

2. Run this command:
bazel build //stratum/hal/bin/barefoot:stratum_bf --define phal_with_onlp=false  --define sde_ver=9.0.0

3. See error
DEBUG: Rule 'com_github_nelhage_rules_boost' modified arguments {"shallow_since": "1576879360 -0800"}
INFO: Build option --define has changed, discarding analysis cache.
ERROR: /root/.cache/bazel/_bazel_root/adebb43308e0307e846fb1a569522202/external/build_bazel_rules_apple/apple/internal/transition_support.bzl:73:26: transition() is experimental and disabled by default. This API is in development and subject to change at any time. Use --experimental_starlark_config_transitions to use this experimental API.
ERROR: /root/bf-sde-9.0.0/stratum/stratum/hal/lib/common/BUILD:508:1: error loading package '@com_github_grpc_grpc//': in /root/.cache/bazel/_bazel_root/adebb43308e0307e846fb1a569522202/external/com_github_grpc_grpc/bazel/grpc_build_system.bzl: in /root/.cache/bazel/_bazel_root/adebb43308e0307e846fb1a569522202/external/build_bazel_rules_apple/apple/ios.bzl: in /root/.cache/bazel/_bazel_root/adebb43308e0307e846fb1a569522202/external/build_bazel_rules_apple/apple/internal/ios_rules.bzl: in /root/.cache/bazel/_bazel_root/adebb43308e0307e846fb1a569522202/external/build_bazel_rules_apple/apple/internal/rule_support.bzl: Extension file 'apple/internal/transition_support.bzl' has errors and referenced by '//stratum/hal/lib/common:hal'
ERROR: Analysis of target '//stratum/hal/bin/barefoot:stratum_bf' failed; build aborted: error loading package '@com_github_grpc_grpc//': in /root/.cache/bazel/_bazel_root/adebb43308e0307e846fb1a569522202/external/com_github_grpc_grpc/bazel/grpc_build_system.bzl: in /root/.cache/bazel/_bazel_root/adebb43308e0307e846fb1a569522202/external/build_bazel_rules_apple/apple/ios.bzl: in /root/.cache/bazel/_bazel_root/adebb43308e0307e846fb1a569522202/external/build_bazel_rules_apple/apple/internal/ios_rules.bzl: in /root/.cache/bazel/_bazel_root/adebb43308e0307e846fb1a569522202/external/build_bazel_rules_apple/apple/internal/rule_support.bzl: Extension file 'apple/internal/transition_support.bzl' has errors
INFO: Elapsed time: 0.362s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (5 packages loaded, 121 targets configured)
    currently loading: @com_google_protobuf// ... (3 packages)

**Expected behavior**
Build shouldn't fail

**Additional context**
root@localhost:~/bf-sde-9.0.0/stratum# git branch
* master

**Comment by pudelkoM** [comment]
We upgraded to Bazel 2.2.0. From the mailing list:

> Hello Stratum developers:
> 
> Today we updated the Bazel version to 2.2.0 (see #84)
> 
> Please run ./setup_dev_env.sh --pull to get new Stratum development container image.

**Comment by pudelkoM** [comment]
Closing now. Reopen is issue still persists after updating Bazel.
