### ISSUE TITLE
add SFP28 support

### ISSUE THREAD

**Issue by habeebmohammed** [stratum/stratum#164]
When plugged in SFP28 optic 25G cable stratum gives an error as "Invalid sfptype"

**Environment**
Run stratum in docker container on Tofino based switch or BSP less mode. 

**To Reproduce**
start the stratum docker and check port status.
Plugin 25G optic cable. SFP28
You can see an error message as "Invalid sfptype" and ports don't link up.

**Expected behavior**
Should support SFP28 and link should come up fine.

**Comment by pudelkoM** [comment]
Closed by 09bcac7aab315e77fb8e30fbe7efc0b07b109371
