### ISSUE TITLE
How can I build stratum(for barefoot) with external toolchains?

### ISSUE THREAD

**Issue by lxlmummy** [stratum/stratum#167]
My product is built on buildroot system with  a third party toolchaintoolchain, as I know, buildroot system needs cmake file，but I see stratum now just supports bazel, not supports cmake, how can I build stratum(for barefoot) for my product ? Could you give me some advices?

**Comment by Yi-Tseng** [comment]
Hi, which toolchain you want to support?
Currently, we only support x86-based architecture.
As far as I know you can add Bazel rules to support different toolchain

**Comment by lxlmummy** [comment]
@Yi-Tseng ，My platform is x86-based architecture，how can I  add Bazel rules to support different toolchain when build stratum bin(for barefoot)，could you give me some related infomations as I am a newer for Bazel?

**Comment by Yi-Tseng** [comment]
If you want to try a different C/C++ compiler, you can set up `CC` and `CXX` environment variable. For example, if you want to use `clang` instead of `gcc`. You can do the following:

```bash
export CC=clang
export CXX=clang++
bazel build [your target....]
```

**Comment by lxlmummy** [comment]
@Yi-Tseng , in my mind, stratum bin for barefoot depend on many targets，if some targets，like protoc which just products proto to be .h .cpp file on host（Ubuntu），how can I do with these targets? When I  set up CC and CXX environment variable with my own toolchain, if this will affect protoc which I want to be compiled with my host gcc? If affect，how can I do?

**Comment by Yi-Tseng** [comment]
According to the protobuf/grpc bazel rules, the protoc binary will be generated automatically by Bazel. I believed that the Bazel will use the compiler you set to build the protoc binary.

**Comment by lxlmummy** [comment]
@Yi-Tseng ，maybe I had not said clear, I means I want stratum binary（for barefoot）to be compiled with by my own toolchain for example clang , at the same time I wish protoc to be compiled with ubuntu host gcc not clang. IF I just set up CC and CXX environment to be clang, protoc will be compiled with clang，which may cause protoc excute error when run command like protoc -I=./  --cpp_out=.  Hellow.pro.

**Comment by pudelkoM** [comment]
Can you explain why you are running protoc manually? Bazel has rules for generating code automatically.

Other than that, I don't see a way the switch the compiler for some targets.

**Comment by Yi-Tseng** [comment]
@lxlmummy, I have no idea how to choose different compiler toolchain for different Bazel target. I'd suggest you send this request to the Bazel team.

**Comment by lxlmummy** [comment]
@Yi-Tseng , thanks a lot！I will request help frome Bazel team.
