### ISSUE TITLE
can see tables after re-loading binaries

### ISSUE THREAD

**Issue by shahid2636** [stratum/stratum#168]
Hi, 
I can see tables after reloading binaries.
Here is what I did.
1. Restart the switch.
2. Recompile with the following command.
      bazel build //stratum/hal/bin/barefoot:stratum_bf --define phal_with_onlp=false --define sde_ver=9.0.0

**Environment**
x86-64-accton-wedge100bf-65x-r0

I  am loading binaries with the following script
   sudo LD_LIBRARY_PATH=$BF_SDE_INSTALL/lib \
        ./bazel-bin/stratum/hal/bin/barefoot/stratum_bf \
         --external_stratum_urls=0.0.0.0:28000 \
         --grpc_max_recv_msg_size=256 \
         --bf_sde_install=$BF_SDE_INSTALL \
         --persistent_config_dir=/root/config \
         --forwarding_pipeline_configs_file=/root/config/tofino_skip_p4.conf \
        --chassis_config_file=/root/config/chassis_config.pb.txt \
         --write_req_log_file=/root/p4_writes.pb.txt \
         --phal_config_path=/root/config/phal_config.pb.txt \
         --bf_sim \
         --bf_switchd_cfg=stratum/hal/bin/barefoot/tofino_skip_p4.conf

**Expected behavior**
I expect to see no tables.

**Outcome **
Still see tables in when reload binaries.
** Here are the logs I see when reloading binaries**
bf_sysfs_fname /sys/class/bf/bf0/device/dev_add
Install dir: /root/bf-sde-9.0.0/install (0x55e99bfdb580)
bf_switchd: system services initialized
bf_switchd: loading conf_file stratum/hal/bin/barefoot/tofino_skip_p4.conf...
bf_switchd: processing device configuration...
Configuration for dev_id 0
  Family        : Tofino
  pci_sysfs_str : /sys/devices/pci0000:00/0000:00:03.0/0000:05:00.0
  pci_domain    : 0
  pci_bus       : 5
  pci_fn        : 0
  pci_dev       : 0
  pci_int_mode  : 1
  sbus_master_fw: /root/bf-sde-9.0.0/install/
  pcie_fw       : /root/bf-sde-9.0.0/install/
  serdes_fw     : /root/bf-sde-9.0.0/install/
  sds_fw_path   : /root/bf-sde-9.0.0/install/
  microp_fw_path:
bf_switchd: processing P4 configuration...
P4 profile for dev_id 0
  p4_name: dummy
    libpd:
    libpdthrift:
    context:
    config:
  Agent[0]: /root/bf-sde-9.0.0/install/lib/libpltfm_mgr.so
  diag:
  accton diag:
  non_default_port_ppgs: 0
  SAI default initialize: 1
bf_switchd: library /root/bf-sde-9.0.0/install/lib/libpltfm_mgr.so loaded
bf_switchd: agent[0] initialized
Tcl server started..
Tcl server: listen socket created
Tcl server: bind done on port 8008, listening...
Tcl server: waiting for incoming connections...
Health monitor started
Operational mode set to ASIC
Initialized the device types using platforms infra API
ASIC detected at PCI /sys/class/bf/bf0/device
ASIC pci device id is 16
bf_switchd: drivers initialized
Skipping P4 program load for dev_id 0
detecting.. IOMMU not enabled on the platform
Setting core_pll_ctrl0=cd44cbfe

bf_switchd: dev_id 0 initialized

bf_switchd: initialized 1 devices
bf_switchd: Credo python server thread initialized..Skip p4 lib init
Skip mav diag lib init
bf_switchd: spawning cli server thread
credo_python_intf: listen socket created
credo_python_intf: bind done on port 9001, listening...
credo_python_intf: listening for incoming connections...
bf_switchd: spawning driver shell
bf_switchd: server started - listening on port 9999
Cannot read termcap database;
using dumb terminal settings.
bf-sde> bf_switchd: starting warm init for dev_id 0 mode 1 serdes_upgrade 0
bf_switchd: agent[0] library unloaded for dev_id 0
bf_switchd: library /root/bf-sde-9.0.0/install/lib/libpltfm_mgr.so loaded
bf_switchd: agent[0] initialized
Tcl server started..
Tcl server: listen socket created
Tcl server: bind done on port 8008, listening...
Tcl server: waiting for incoming connections...
Health monitor started
Skip diag lib deinit
E0327 04:14:35.039280  8411 hal.cc:234] Stratum external facing services are listening to 0.0.0.0:28000, localhost:28000...
pipe
bf-sde> pipe_mgr E0327 04:14:38.039680231    8474 ev_epollex_linux.cc:493]    Error shutting down fd 74. errno: 9
E0327 04:14:38.041143  8411 hal.cc:376] StratumErrorSpace::ERR_INTERNAL: Failed to check in with procmon: failed to connect to all addresses
E0327 04:14:38.042419  8411 hal.cc:244] Error when checking in with procmon: Failed to check in with procmon: failed to connect to all addresses.

**Comment by pudelkoM** [comment]
What tables are you referring to? From the log I cannot see what you mean.

Assuming you mean P4 tables and pushed a pipeline config before the restart, it is expected to see the same pipeline being programmed after reboot. That's why we save it in `--forwarding_pipeline_configs_file` in the first place.
