### ISSUE TITLE
why SessionTemp class not contain device_id ？

### ISSUE THREAD

**Issue by lxlmummy** [stratum/stratum#169]
Hi, when I read the source code, for the "batch" featuie for p4runtime spect，stratum seems just create a SessionTemp obj which does not contain device_id？ my question is why not contain device_id?  For multi-line-card(multi device id),  I think one SessionTemp just deal with one device id，do I understand not correct?  This issue is equivalent to question why P4lang/PI project designs target APIs which do not contain devce_id param, like __pi_session_init，_pi_session_cleanup，_pi_batch_begin，_pi_batch_end.
so for __pi_session_init API，
why design as
__pi_session_init(pi_session_handle_t *session_handle)__
why not design as
__pi_session_init(pi_dev_id_t dev_id, pi_session_handle_t *session_handle)__
    If I understand something wrong about p4runtime spect？or this is a bug?

**Comment by pudelkoM** [comment]
Can you explain what you mean? Which source code did you read? Which SessionTemp do you mean?

**Comment by Yi-Tseng** [comment]
In Stratum, we use the DeviceMgr class to pass P4Runtime requests to the lower level (SDE, bmv2)
https://github.com/p4lang/PI/blob/master/proto/frontend/PI/frontends/proto/device_mgr.h

The device ID value is included in the P4Runtime request, which will pass to the DeviceMgr directly, for example, the `WriteRequest`:
https://github.com/p4lang/p4runtime/blob/master/proto/p4/v1/p4runtime.proto#L63

If you are asking the API design of p4lang/PI project, please open an issue [here](https://github.com/p4lang/PI/issues/new)

**Comment by lxlmummy** [comment]
@Yi-Tseng @pudelkoM , thanks very much!  It is an issue belong to P4lang/PI，I will open an issue there，close this isssu.
