### ISSUE TITLE
Issue in installing BMV2

### ISSUE THREAD

**Issue by drobinkent** [stratum/stratum#17]
While trying to install the bmv2 , I am getting following error 

> src/pi_imp.cpp: In function ‘pi_status_t _pi_init(int*, void*)’:
> src/pi_imp.cpp:65:13: error: conflicting declaration of C function ‘pi_status_t _pi_init(int*, void*)’
>  pi_status_t _pi_init(int *abi_version, void *extra) {
>              ^~~~~~~~
> In file included from src/pi_imp.cpp:26:0:
> /usr/local/include/PI/target/pi_imp.h:30:13: note: previous declaration ‘pi_status_t _pi_init(void*)’
>  pi_status_t _pi_init(void *extra);
>              ^~~~~~~~
> src/pi_imp.cpp:68:18: error: ‘PI_ABI_VERSION’ was not declared in this scope
>    *abi_version = PI_ABI_VERSION;
>                   ^~~~~~~~~~~~~~
> src/pi_imp.cpp:68:18: note: suggested alternative: ‘_SC_VERSION’
>    *abi_version = PI_ABI_VERSION;
>                   ^~~~~~~~~~~~~~
>                   _SC_VERSION
> Makefile:537: recipe for target 'src/pi_imp.lo' failed
> make[2]: *** [src/pi_imp.lo] Error 1
> make[2]: *** Waiting for unfinished jobs....
> libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -I../include -I../include -isystem../third_party/jsoncpp/include -isystem../third_party/spdlog -I../targets/simple_switch -DWITH_SIMPLE_SWITCH -isystem/include -Wall -Wextra -pthread -g -O2 -MT src/group_selection.lo -MD -MP -MF src/.deps/group_selection.Tpo -c src/group_selection.cpp -o src/group_selection.o >/dev/null 2>&1
> libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -I../include -I../include -isystem../third_party/jsoncpp/include -isystem../third_party/spdlog -I../targets/simple_switch -DWITH_SIMPLE_SWITCH -isystem/include -Wall -Wextra -pthread -g -O2 -MT src/pi_clone_imp.lo -MD -MP -MF src/.deps/pi_clone_imp.Tpo -c src/pi_clone_imp.cpp -o src/pi_clone_imp.o >/dev/null 2>&1
> make[2]: Leaving directory '/home/deba/bmv2_install/bmv2/PI'
> Makefile:454: recipe for target 'all-recursive' failed
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory '/home/deba/bmv2_install/bmv2'
> Makefile:384: recipe for target 'all' failed
> make: *** [all] Error 2
>

**Comment by drobinkent** [comment]
After doing the steps freshly, when I try to complete the step of **"Running the stratum_bmv2 binary
"** 

I face following problem

**bazel build //stratum/hal/bin/bmv2:stratum_bmv2
ERROR: /home/deba/stratum/bazel/workspace_rule.bzl:19:1: load() statements must be called before any other statement. First non-load() statement appears at /home/deba/stratum/bazel/workspace_rule.bzl:17:1. Use --incompatible_bzl_disallow_load_after_statement=false to temporarily disable this check.
ERROR: error loading package '': in /home/deba/stratum/bazel/rules/build_tools.bzl: Extension 'bazel/workspace_rule.bzl' has errors
ERROR: error loading package '': in /home/deba/stratum/bazel/rules/build_tools.bzl: Extension 'bazel/workspace_rule.bzl' has errors
INFO: Elapsed time: 0.075s
INFO: 0 processes.**

Any help ?

**Comment by Yi-Tseng** [comment]
Hi @drobinkent , We are using Bazel version 0.23.2 in our environment and plain to upgrade the Bazel version to 1.0.0

If you want to try new version of Bazel, please follow the suggestion from your Bazel log to build it:
```
Use --incompatible_bzl_disallow_load_after_statement=false to temporarily disable this check.
```

**Comment by playsand** [comment]
I have a problem when I executed "bazel build //stratum/hal/bin/bmv2:stratum_bmv2"
```
bazel build //stratum/hal/bin/bmv2:stratum_bmv2  --incompatible_bzl_disallow_load_after_statement=false  --incompatible_disable_deprecated_attr_params=false
INFO: Writing tracer profile to '/root/.cache/bazel/_bazel_root/096eb34d74939df26d8ec3f987c86d06/command.profile.gz'
ERROR: /root/stratum/stratum/hal/bin/bmv2/BUILD:24:1: file '//bazel:rules.bzl' does not contain symbol 'stratum_cc_binary'
ERROR: /root/stratum/stratum/hal/bin/bmv2/BUILD:26:1: name 'stratum_cc_binary' is not defined
ERROR: error loading package 'stratum/hal/bin/bmv2': Package 'stratum/hal/bin/bmv2' contains errors
INFO: Elapsed time: 3.141s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
```

**Comment by Yi-Tseng** [comment]
I would suggest using the containerized environment to build the Stratum. It should include every necessary libraries and tool to build the binary.
https://github.com/stratum/stratum#development-environment

The `./setup_dev_env.sh` script mounts the Stratum dir into the container, so you can edit the code using your IDE on your host machine and get the binary from the host machine after it compiled.

**Comment by pudelkoM** [comment]
Closing for now. Please reopen if the issues still persist.

**Comment by drobinkent** [comment]
The issue persists. 

```
DEBUG: Call stack for the definition of repository 'build_stack_rules_proto' which is a http_archive (rule definition at /home/deba/.cache/bazel/_bazel_deba/867697089ae78c5b510d61904b21961d/external/bazel_tools/tools/build_defs/repo/http.bzl:262:16):
 - /home/deba/stratum/bazel/workspace_rule.bzl:62:5
 - /home/deba/stratum/bazel/workspace_rule.bzl:144:22
 - /home/deba/stratum/bazel/deps.bzl:87:9
 - /home/deba/stratum/WORKSPACE:55:1
ERROR: /home/deba/stratum/stratum/hal/bin/bmv2/BUILD:24:1: file '//bazel:rules.bzl' does not contain symbol 'stratum_cc_binary'
ERROR: /home/deba/stratum/stratum/hal/bin/bmv2/BUILD:26:1: name 'stratum_cc_binary' is not defined
ERROR: error loading package 'stratum/hal/bin/bmv2': Package 'stratum/hal/bin/bmv2' contains errors
INFO: Elapsed time: 25.817s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
```


Any help will be highly appreciated. 

I need to work with the bmv2 project and stratum project together. If you have the script for building the whole project with bmv2, that would be really great.

**Comment by pudelkoM** [comment]
Can you confirm you are using Bazel 0.23.2? (`bazel version`)

I also think the README is outdated about installing PI and bmv2 first. Building bmv2 (`//stratum/hal/bin/bmv2:stratum_bmv2`) in the dev container just works out-of-the-box.

Are you trying a native build?

**Comment by drobinkent** [comment]
Returning back to bazel 0.23.2 solves the problem of installing bmv2. 

Yes, I am trying a native build.

**Comment by drobinkent** [comment]
Where to find the details of native installation?

**Comment by pudelkoM** [comment]
There are no instructions for that. Your best bet is mimicking the [build docker image](https://github.com/stratum/stratum/blob/master/Dockerfile.build) as close as possible. 
I was also wrong about the PI/bmv2 deps, we still [install them](https://github.com/stratum/stratum/blob/master/Dockerfile.build#L70-L91).

I might be easier to build in docker and then copy the binary out.
