### ISSUE TITLE
Tofino connected port become DOWN

### ISSUE THREAD

**Issue by Muthuramane** [stratum/stratum#175]
**Describe the bug**

The tofino port's operating status is showing as DOWN.

Attached Edge-Core(Model name: ET5402-DAC-3M) break-out cable to Tofino switch port 1 and other end connected to 4hosts(10G HBA from Intel 82599ES X520-1). 

In chasis_config.pb.txt file, the configuration of Port1 specified like ids 188, 189, 190, and 191. 

singleton_ports {
   id: 188
   name: "1/0"
   slot: 1
   port: 1
   speed_bps: 10000000000
   config_params {
      admin_state: ADMIN_STATE_ENABLED
      autoneg: TRI_STATE_TRUE
   }
   node: 1
}

**Environment**
x86-64-accton-wedge100bf-65x-r0

If building from source:
$ bazel version
Build label: 0.23.2
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Mar 11 16:47:03 2019 (1552322823)
Build timestamp: 1552322823
Build timestamp as int: 1552322823

$cat /etc/onl/platform
x86-64-accton-wedge100bf-65x-r0

$uname -a
Linux localhost 4.14.49-OpenNetworkLinux #1 SMP Sat May 4 16:37:07 UTC 2019 x86_64 GNU/Linux

$lsmod
Module Size Used by
bf_kdrv 28672 0
x86_pkg_temp_thermal 16384 0
gpio_ich 16384 0
optoe 20480 0

**To Reproduce**
1. Run the stratum by 
sudo LD_LIBRARY_PATH=$BF_SDE_INSTALL/lib \
     ./bazel-bin/stratum/hal/bin/barefoot/stratum_bf \
       --external_stratum_urls=0.0.0.0:28000 \
       --grpc_max_recv_msg_size=256 \
       --bf_sde_install=$BF_SDE_INSTALL \
       --persistent_config_dir=/root/config \
       --forwarding_pipeline_configs_file=/root/config/tofino_skip_p4.conf \
       --chassis_config_file=/root/config/chassis_config.pb.txt \
       --write_req_log_file=/root/p4_writes.pb.txt \
       --phal_config_path=/root/config/phal_config.pb.txt \
       --bf_sim \
       --bf_switchd_cfg=stratum/hal/bin/barefoot/tofino_skip_p4.conf

2. In ONOS, activated "barefoot" driver and my own pipeline configs. The pipeline of tofino switch successfully pushed by ONOS and able to see the table entries.

3. The Tofino connected host port status become DOWN.

4. ONOS CLI/GUI show the port's state as disbaled/false respectively.

5. I tried manually enable the port on tofino CLI as well as through ONOS CLI. But, either way didn't help to bring UP the ports.

**Expected behavior**
Port should become UP

**Comment by Yi-Tseng** [comment]
HI @Muthuramane 

I assume the chassis config you are using is correct (node, port, slot, id, name...) 

Which commit of Stratum you are using? The current version uses Bazel 2.2.0 to build the binary instead of 0.23.2.

The flag "--forwarding_pipeline_configs_file" you are using to start the Stratum is not correct. 
This flag tells Stratum where to store the pipeline config when the controller pushes it and can load the pipeline config next time when you restart the Stratum.

> 3. The Tofino connected host port status becomes DOWN.

If I understand correctly, ports are UP before you push the pipeline config. Can you verify if there is no error when you push the pipeline config? The pipeline config should not affect the port state in theory.

Can you also check the link state on server side? You can use the `ip` command to verify it. Also, you can check the system log, there should be a message like:
```
ixgbe 0000:04:00.1 enp4s0f1: NIC Link is Up 10 Gbps, Flow Control: RX/TX
```

**Comment by Muthuramane** [comment]
Hi Yi,

The source code of stratum from one of my colleague and not sure about the version but the latest commit log on below

root@localhost:~/bf-sde-9.0.0/bk-stratum# git log -1
commit 3fac1374d241e6921319ef39496f968efc87844d
Author: Yi Tseng <yi@opennetworking.org>
Date:   Wed Feb 12 17:40:07 2020 -0800

    New Barefoot binary without ONLP support (#111)

>>>Which commit of Stratum you are using? The current version uses Bazel 2.2.0 to build the binary instead of 0.23.2.
[Muthu] We encounter the problem with latest stratum code with Bazel 2.2.0 that's why we back to working one.

>>>The flag "--forwarding_pipeline_configs_file" you are using to start the Stratum is not correct.
This flag tells Stratum where to store the pipeline config when the controller pushes it and can load the pipeline config next time when you restart the Stratum.
[Muthu] That means, I can specify the any filename. Is it correct?

>>>If I understand correctly, ports are UP before you push the pipeline config. Can you verify if there is no error when you push the pipeline config? The pipeline config should not affect the port state in theory.
[Muthu] Yes, I confirmed the problem with Tofino switch and Host conected port's signal issue. 
I seen the log message of /var/log/kern.log and it shows only SFP detected message only not related to signal. 
 
The ethtool settings of my connected host 
Settings for enp2s0:
	Supported ports: [ FIBRE ]
	Supported link modes:   10000baseT/Full 
	Supported pause frame use: Symmetric
	Supports auto-negotiation: No
	Supported FEC modes: Not reported
	Advertised link modes:  10000baseT/Full 
	Advertised pause frame use: Symmetric
	Advertised auto-negotiation: No
	Advertised FEC modes: Not reported
	Speed: Unknown!
	Duplex: Unknown! (255)
	Port: Direct Attach Copper
	PHYAD: 0
	Transceiver: internal
	Auto-negotiation: off
	Supports Wake-on: d
	Wake-on: d
	Current message level: 0x00000007 (7)
			       drv probe link
	Link detected: no


Looks this problem is not related to the Stratum application and closing this issue.

Please, check my comments and let me know your conclusion.

**Comment by Muthuramane** [comment]
Hi Yi,

I fixed the signal issue between host and tofino. 

Confirmed the port link status UP before push the forwarding pipeline to the tofino device through ONOS.

1/0  |31/0|188|1/60| 10G  |NONE|YES|ENB|UP |  NONE  |              37|               0| 
1/1  |31/1|189|1/61| 10G  |NONE|YES|ENB|UP |  NONE  |               2|               0| 

After issue the command "onos-netcfg localhost topo-without-ports.json", the port become offline.

The following prints are seen in the tofino device

bf-sde.pm> bf_switchd: starting warm init for dev_id 0 mode 1 serdes_upgrade 0 
bf_switchd: agent[0] library unloaded for dev_id 0
bf_switchd: library /root/bf-sde-9.0.0/install/lib/libpltfm_mgr.so loaded
bf_switchd: agent[0] initialized
Tcl server started..
Tcl server: listen socket created
Tcl server: bind done on port 8008, listening...
Tcl server: waiting for incoming connections...
Health monitor started 
Skip diag lib deinit
/E0406 08:51:31.536453  5753 bf_chassis_manager.cc:374] StratumErrorSpace::ERR_INVALID_PARAM: 'port_id_to_config != nullptr' is false. Node 0 is not configured or not known.
E0406 08:51:31.536574  5753 bf_chassis_manager.cc:429] Return Error: GetPortConfig( request.port_speed().node_id(), request.port_speed().port_id()) at stratum/hal/lib/barefoot/bf_chassis_manager.cc:429
E0406 08:51:31.536921  5753 bf_switch.cc:205] StratumErrorSpace::ERR_INTERNAL: Not supported yet
E0406 08:51:31.537266  5753 bf_switch.cc:205] StratumErrorSpace::ERR_INTERNAL: Not supported yet

1/0  |31/0|188|1/60| 10G  |NONE|YES|ENB|DWN|  NONE  |               0|               0| 
1/1  |31/1|189|1/61| 10G  |NONE|YES|ENB|DWN|  NONE  |               0|               0| 

I manually reconfigure the port then status become UP. 

Why the tofino switch port status become DOWN after pushing the forwarding pipeline of that device?

**Comment by Yi-Tseng** [comment]
Hi Muthuramane,

According to your log

>  /E0406 08:51:31.536453 5753 bf_chassis_manager.cc:374] StratumErrorSpace::ERR_INVALID_PARAM: 'port_id_to_config != nullptr' is false. Node 0 is not configured or not known.

This shows that the chassis config which pushed to the chassis manager is incorrect. Can you show me the chassis config you are using?

**Comment by Yi-Tseng** [comment]
>  [Muthu] We encounter the problem with latest stratum code with Bazel 2.2.0 that's why we back to working one.

Please let the team know the issue you are facing in another issue ticket, thanks

>  [Muthu] That means, I can specify the any filename. Is it correct?

Yes, as long as you can access the directory and be able to place file there

**Comment by Muthuramane** [comment]
The root cause of this issue, specified "autoneg" config parameter as TRI_STATE_TRUE instead of TRI_STATE_FALSE  in singleton_ports{}.

Closing this issue.
