### ISSUE TITLE
occurrence FATALException of libprotobuf at Running the binary

### ISSUE THREAD

**Issue by baekguihyun** [stratum/stratum#188]
**Describe the bug**
Hello, Developer.

I used Barefoot Whitebox Switch (Edgecore Wedge100BF-32X), and tried to run stratum after build stratum by bazel.
This stratum succeeded in building, but the it execution has the following error:
----------------------------------------------------------------------------------------------
> root@localhost:~/stratum#      ./bazel-bin/stratum/hal/bin/barefoot/stratum_bf \
>        --external_stratum_urls=0.0.0.0:28000 \
>        --grpc_max_recv_msg_size=256 \
>        --bf_sde_install=$BF_SDE_INSTALL \
>        --persistent_config_dir=/root/stratum/stratum/hal/bin/barefoot \
>        --forwarding_pipeline_configs_file=/root/stratum/stratum/hal/bin/barefoot/p4_pipeline.pb.txt \
>        --chassis_config_file=/root/stratum/stratum/hal/bin/barefoot/chassis_config.pb.txt \
>        --write_req_log_file=/root/stratum/stratum/hal/bin/barefoot/p4_writes.pb.txt \
>        --bf_sim
[libprotobuf FATAL external/com_google_protobuf/src/google/protobuf/generated_message_util.cc:809] CHECK failed: (scc->visit_status.load(std::memory_order_relaxed)) == (SCCInfoBase::kRunning):
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: (scc->visit_status.load(std::memory_order_relaxed)) == (SCCInfoBase::kRunning):
Aborted
----------------------------------------------------------------------------------------------
**Environment**
stratum commit: c5ca80308697a032f54490def0be33e82031bcfe
bazel version: 
Build label: 2.2.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Mar 3 09:26:12 2020 (1583227572)
Build timestamp: 1583227572
Build timestamp as int: 1583227572

Switch:
```bash
cat /etc/onl/platform               : x86-64-accton-wedge100bf-32x-r0
uname -a                                 : Linux localhost 4.14.151-OpenNetworkLinux #1 SMP Wed Apr 8 01:15:26 UTC 2020 x86_64 GNU/Linux

lsmod                                       :

Module                  Size  Used by
bf_kdrv                28672  0
pmbus                  16384  0
pmbus_core             28672  1 pmbus
x86_pkg_temp_thermal    16384  0
gpio_ich               16384  0
optoe                  20480  0

BF-SDE version is "9.0.0".

```

**To Reproduce**
1. Use this config is default setup.
2. Run this command is
  ./bazel-bin/stratum/hal/bin/barefoot/stratum_bf \
        --external_stratum_urls=0.0.0.0:28000 \
        --grpc_max_recv_msg_size=256 \
        --bf_sde_install=$BF_SDE_INSTALL \
        --persistent_config_dir=/root/stratum/stratum/hal/bin/barefoot \
        --forwarding_pipeline_configs_file=/root/stratum/stratum/hal/bin/barefoot/p4_pipeline.pb.txt \
        --chassis_config_file=/root/stratum/stratum/hal/bin/barefoot/chassis_config.pb.txt \
        --write_req_log_file=/root/stratum/stratum/hal/bin/barefoot/p4_writes.pb.txt \
        --bf_sim
3. See error
[libprotobuf FATAL external/com_google_protobuf/src/google/protobuf/generated_message_util.cc:809] CHECK failed: (scc->visit_status.load(std::memory_order_relaxed)) == (SCCInfoBase::kRunning):
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: (scc->visit_status.load(std::memory_order_relaxed)) == (SCCInfoBase::kRunning):
Aborted

**Expected behavior**
A clear and concise description of what you expected to happen. : There isn't.

**Additional context**
Add any other context about the problem here. : There isn't.

**Comment by pudelkoM** [comment]
I found these two issues that could be related:

https://github.com/protocolbuffers/protobuf/issues/5923

https://github.com/protocolbuffers/protobuf/issues/6074

First thing to try is using clang instead of gcc: `export CC=clang; export CXX=clang++` and rebuild.

**Comment by baekguihyun** [comment]
Thanks for your answer.

I installed CLANG and rebuilt Stratum with this solution, but the same error occurred again in the execution command. I also rebuilt Protobuf-3.8.0.
In all of the above cases, there are errors in the build, but I get errors when I run. 

What's the problem?

**Comment by pudelkoM** [comment]
> I installed CLANG

How exactly are you building Stratum right now?

**Comment by baekguihyun** [comment]
I don't used development container and Docker, and used the this command for building:

>bazel build //stratum/hal/bin/barefoot:stratum_bf \
>    --define sde_ver=$(cat $SDE_INSTALL/share/VERSION) \
>    --define phal_with_onlp=false

**Comment by pudelkoM** [comment]
That might be the source of this error. Can you try a build from Docker, just to exclude that factor?

**Comment by baekguihyun** [comment]
Thank you~
Do I need to build a BF-SDE from the development container?

**Comment by pudelkoM** [comment]
Not sure that's necessary. @Yi-Tseng do you know more about that?

**Comment by baekguihyun** [comment]
> Not sure that's necessary. @Yi-Tseng do you know more about that?

**Comment by baekguihyun** [comment]
> > Not sure that's necessary. @Yi-Tseng do you know more about that?

I have another question between BF-SDE and Stratum. This is related to the question.
When I built BF-SDE, I installed most of the components using interactive mode. However, README applies the Stratum-profile. Then, can this be a problem? I built it in the above method and ran it on the development container, and there was an error related to the Thrift library.

**Comment by baekguihyun** [comment]
> Not sure that's necessary. @Yi-Tseng do you know more about that?

I have another question between BF-SDE and Stratum. This is related to the question.
When I built BF-SDE, I installed most of the components using interactive mode. However, README applies the Stratum-profile. Then, can this be a problem? I built it in the above method and ran it on the development container, and there was an error related to the Thrift library.

**Comment by Yi-Tseng** [comment]
> Thank you~
> Do I need to build a BF-SDE from the development container?

Hi @baekguihyun,

I would suggest building the SDE in the development container since we don't know which kinds of toolchain you are using and not sure the SDE you built can work with toolchains in the development container.
However, you can still try to copy the entire $SDE_INSTALL directory (default is `sde/install`) to the container and set the `BF_SDE_INSTALL` environment variable to that directory.

I also tried to build the Stratum in my switch (Debian 9 based OpenNetworkLinux) and it works fine.

**Comment by Yi-Tseng** [comment]
> I have another question between BF-SDE and Stratum. This is related to the question.

Hi, If you are using SDE 8.9.2, you need to remove the thrift package from the Stratum profile manually.

This is how we build the SDE in the container:
https://github.com/stratum/stratum/blob/master/stratum/hal/bin/barefoot/docker/Dockerfile.builder#L38-L40

**Comment by baekguihyun** [comment]
Thanks for your answer.
I solved this problem with your solution.

I built SDE and Stratum from the development container in my switch and executed them on the host, and it was solved. However, the "Connection Refused" error is repeated when the Stratum is built and executed in BSP mode. 

--------------------
  Family        : Tofino
  pci_sysfs_str : /sys/devices/pci0000:00/0000:00:03.0/0000:05:00.0
  pci_domain    : 0
  pci_bus       : 5
  pci_fn        : 0
  pci_dev       : 0
  pci_int_mode  : 1
  sbus_master_fw: /usr/local/
  pcie_fw       : /usr/local/
  serdes_fw     : /usr/local/
  sds_fw_path   : /usr/local/
  microp_fw_path:
bf_switchd: processing P4 configuration...
P4 profile for dev_id 0
  p4_name: dummy
    libpd:
    libpdthrift:
    context:
    config:
  Agent[0]: /usr/local/lib/libpltfm_mgr.so
  diag:
  accton diag:
  non_default_port_ppgs: 0
  SAI default initialize: 1
Operational mode set to default: MODEL
bf_switchd: initializing dru_sim service
bf_switchd: library libdru_sim.so loaded
INFO: DRU sim MTI initialized successfully
dru_sim: client socket created
connect failed. Error: Connection refused
connect failed. Error: Connection refused
connect failed. Error: Connection refused
connect failed. Error: Connection refused
connect failed. Error: Connection refused
connect failed. Error: Connection refused
connect failed. Error: Connection refused
connect failed. Error: Connection refused

--------------------

**Comment by Yi-Tseng** [comment]
> Thanks for your answer.
> I solved this problem with your solution.
> 
> I built SDE and Stratum from the development container in my switch and executed them on the host, and it was solved. However, the "Connection Refused" error is repeated when the Stratum is built and executed in BSP mode.
> 
> Family : Tofino
> pci_sysfs_str : /sys/devices/pci0000:00/0000:00:03.0/0000:05:00.0
> pci_domain : 0
> pci_bus : 5
> pci_fn : 0
> pci_dev : 0
> pci_int_mode : 1
> sbus_master_fw: /usr/local/
> pcie_fw : /usr/local/
> serdes_fw : /usr/local/
> sds_fw_path : /usr/local/
> microp_fw_path:
> bf_switchd: processing P4 configuration...
> P4 profile for dev_id 0
> p4_name: dummy
> libpd:
> libpdthrift:
> context:
> config:
> Agent[0]: /usr/local/lib/libpltfm_mgr.so
> diag:
> accton diag:
> non_default_port_ppgs: 0
> SAI default initialize: 1
> Operational mode set to default: MODEL
> bf_switchd: initializing dru_sim service
> bf_switchd: library libdru_sim.so loaded
> INFO: DRU sim MTI initialized successfully
> dru_sim: client socket created
> connect failed. Error: Connection refused
> connect failed. Error: Connection refused
> connect failed. Error: Connection refused
> connect failed. Error: Connection refused
> connect failed. Error: Connection refused
> connect failed. Error: Connection refused
> connect failed. Error: Connection refused
> connect failed. Error: Connection refused
> 
> I executed the following command.
> `./bazel-bin/stratum/hal/bin/barefoot/stratum_bf -flagfile=/stratum_configs/stratum.flags`
> And I executed it with the attached file.
> [stratum_configs.zip](https://github.com/stratum/stratum/files/4473164/stratum_configs.zip)

According to your logs, it seems the SDE library thinks that you are using Tofino model instead of the real hardware. And it will try to connect to the model via TCP.
Can you try to reload the Barefoot kernel module and check if `/dev/bf0` device exists ?

**Comment by baekguihyun** [comment]
I ran the following command and it worked properly.
`
/bazel-bin/stratum/hal/bin/barefoot/stratum_bf \
   --external_stratum_urls=0.0.0.0:28000 \
   --grpc_max_recv_msg_size=256 \
   --bf_sde_install=$BF_SDE_INSTALL \
   --persistent_config_dir=$STRATUM_HOME/stratum/hal/bin/barefoot \
   --forwarding_pipeline_configs_file=$STRATUM_HOME/stratum/hal/bin/barefoot/p4_pipeline.pb.txt \
   --chassis_config_file=$STRATUM_HOME/stratum/hal/bin/barefoot/chassis_config.pb.txt \
   --write_req_log_file=$STRATUM_HOME/stratum/hal/bin/barefoot/p4_writes.pb.txt \
   --phal_config_path=$STRATUM_HOME/stratum/hal/config/x86-64-accton-wedge100bf-32x-r0/phal_config.pb.txt \
   --bf_switchd_cfg=$STRATUM_HOME/stratum/hal/bin/barefoot/tofino_skip_p4.conf \
   --bf_sim
`
Thank  you very much again for your hard work!
