### ISSUE TITLE
Missing P4Runtime Python bindings from mn-stratum image

### ISSUE THREAD

**Issue by ccascone** [stratum/stratum#205]
Instead of `.py` files, the image contains `.cc` and `.h` files in the corresponding python package location.

To reproduce the issue:
```
docker pull opennetworking/mn-stratum:latest
docker run --rm -it --entrypoint bash opennetworking/mn-stratum:latest
root@a43a429b0a76:~# ls /usr/local/lib/python2.7/dist-packages/p4/v1/
__init__.py  p4data.pb.cc  p4data.pb.h  p4runtime.grpc.pb.cc  p4runtime.grpc.pb.h  p4runtime.pb.cc  p4runtime.pb.h
```

**Comment by ccascone** [comment]
For reference, here's what the content of the `p4` python package looked like in an older version of the image:

```
root@2a34fa814042:~# ls -R /usr/local/lib/python2.7/dist-packages/p4/
/usr/local/lib/python2.7/dist-packages/p4/:
__init__.py  config  v1

/usr/local/lib/python2.7/dist-packages/p4/config:
__init__.py  v1

/usr/local/lib/python2.7/dist-packages/p4/config/v1:
__init__.py  p4info_pb2.py  p4info_pb2_grpc.py  p4types_pb2.py  p4types_pb2_grpc.py

/usr/local/lib/python2.7/dist-packages/p4/v1:
__init__.py  p4data_pb2.py  p4data_pb2_grpc.py  p4runtime_pb2.py  p4runtime_pb2_grpc.py
```

**Comment by pudelkoM** [comment]
Do you have the image hash? Or even better, does it have a `vcs-ref`?

`docker image inspect 6dd9b3009eb2 | grep vcs-ref`

**Comment by pudelkoM** [comment]
I found the issue and started a fix: #206 

Nothing depends on these files, so bazel does not build them.

This is a good opportunity to stop using brittle hacks and start writing down all dependencies explicitly, so that this does not happen in the future.

**Comment by ccascone** [comment]
It looks like my older image doesn't have a `vcs-ref` label:

```
➜  ~ docker images | grep mn-stratum
opennetworking/mn-stratum   <none>    6dd9b3009eb2        44 hours ago        228MB
opennetworking/mn-stratum   latest    abcf54d49608        7 months ago        169MB
➜  ~ docker image inspect abcf54d49608 | grep vcs-ref
➜  ~
```

**Comment by bocon13** [comment]
Explore packing the p4rt files as a python package/wheel in bazel and installing it into the container
