### ISSUE TITLE
np4_intel platform build is broken

### ISSUE THREAD

**Issue by craigsdell** [stratum/stratum#230]
**Describe the bug**
The np4_intel platform build fails on stratum/hal/bin/np4intel/main.cc Main function as per the messages below in this issue.

**Environment**
Using the `setup_dev_env.sh --np4-intel` containerised bazel build environment to build the np4_intel binary using the following command:
bazel build //stratum/hal/bin/np4_intel:stratum_np4intel

If building from source:
`bazel version`
Starting local Bazel server and connecting to it...
Build label: 2.2.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Mar 3 09:26:12 2020 (1583227572)
Build timestamp: 1583227572
Build timestamp as int: 1583227572

Switch:
Intel PAC N3000

**To Reproduce**
1. setup_dev_env.sh --np4-intel
2. bazel build //stratum/hal/bin/np4_intel:stratum_np4intel
3. See these errors
stratum/hal/bin/np4intel/main.cc: In function 'int stratum::hal::np4intel::Main(int, char**)':
stratum/hal/bin/np4intel/main.cc:142:56: error: 'class util::StatusOr<std::unique_ptr<stratum::CredentialsManager> >' has no member named 'get'
                                    credentials_manager.get());
                                                        ^~~
Target //stratum/hal/bin/np4intel:stratum_np4intel failed to build

**Expected behavior**
The build should complete successfully.

**Additional context**
I believe this was introduced in the original PR for the np4_intel platform during one of the merges from master.

**Comment by pudelkoM** [comment]
Yi updated the CredentialsManager recently, it's `statusOr<unique_ptr>` now.

**Comment by craigsdell** [comment]
> Yi updated the CredentialsManager recently, it's `statusOr<unique_ptr>` now.

yes I noticed thanks Max.  I've created the appropriate changes and I'm pulling together a PR now, together with a change to also check the MD5 checksum on the Netcope SDK in the container build process.

**Comment by pudelkoM** [comment]
Sure. When looking into it, I saw other things that I fixed: https://github.com/stratum/stratum/pull/232
