### ISSUE TITLE
Investigate if BF SDE dependecy can be improved

### ISSUE THREAD

**Issue by pudelkoM** [stratum/stratum#241]
Instead of relying on the env variable to be set and the SDE to be built with all the correct parameters, we could make this a two-step process.

1. Build the SDE for a given SDE version and Kernel version
 - Single script or container, supplied in Stratum
 - Results in one tarball + checksum
2. Bazel depends on this tarball via `file:///some/path`

Pros:
- Tarball be shared, saves time
- Harder to get wrong

**Comment by bocon13** [comment]
fixed by #367
