### ISSUE TITLE
Stratum: how to initiate support with different ports of gnmi and stratum p4runtime

### ISSUE THREAD

**Issue by lxlmummy** [stratum/stratum#270]
Since I have just learned stratum,   can Gnmi service with different port from P4Runtime service, such as P4Runtime service with ports 50001 and GNMI service with ports 50002? If stratum supports so, how to set parameters with stratum-bmv2 to  run？

**Comment by pudelkoM** [comment]
Yes and no. All services run in the same gRPC server and cannot be separated by ports.
But you can make the server listen on multiple ports instead and then use them for a single purpose:

`start-stratum.sh --external_stratum_urls=0.0.0.0:50001,0.0.0.0:50002`

**Comment by lxlmummy** [comment]
ok, thanks~
