### ISSUE TITLE
Add Q&A section to stratum_bf README

### ISSUE THREAD

**Issue by pudelkoM** [stratum/stratum#274]
Structure should be:
### Error message
\<solution>

E.g. about this issue: https://github.com/stratum/stratum/commit/5851cdec95beeaa87b726e304ae6a924bd995364#diff-bde003393b92a53cbcb2ca4aa9c31986L172-L183

**Comment by Yi-Tseng** [comment]
Maybe FAQs is better?
Frequently Asked Questions (FAQs) and answers

**Comment by pudelkoM** [comment]
Completely agree. Q&A is interactive.

In the actual PR it's called "Troubleshooting" section.
