### ISSUE TITLE
Question regarding P4Runtime `Read` RPC

### ISSUE THREAD

**Issue by davidgengenbach** [stratum/stratum#289]
As far as I can tell from the code only, Stratum does not return a stream of `ReadResponses` when called via the `Read` RPC.

`P4Service` goes to `SwitchInterface` (sub-class) goes to `PINode` which calls into the PI library using the `DeviceMgr.read(...)`:
https://github.com/stratum/stratum/blob/a0b39ae472a72c0bcefd341011cc9df7dea8b368/stratum/hal/lib/pi/pi_node.cc#L158-L175

The `DeviceMgr.read(..)` method does not take a writer as input but a single response.

I do not see any loops, timeouts or something similar there which would indicate that responses are streamed. 
According to the P4Runtime specification, the [`Read` RPC should return a stream](https://p4.org/p4runtime/spec/master/P4Runtime-Spec.html#sec-read-rpc), as far as I understood.

Thanks in advance for answering!

**Comment by pudelkoM** [comment]
Please also read section 13.3.1 under Batch Processing

> There is no requirement that each request in the batch will correspond to one ReadResponse message in the stream. The stream-based design for response message is to avoid memory pressure on the P4Runtime server when the Read results in a very large number of entities to be returned. The P4Runtime server is free to break them apart across multiple response messages as it sees fit. 

A single request MAY be split into multiple responses. PI does not have such a interface.

**Comment by davidgengenbach** [comment]
Ah, okay. Understood.

I know it is out of scope for Stratum but somehow retrieving a stream of statistics from a switch seems like a common use-case - one where performance, e.g., the delay, can play an important role.
Adding the overhead of unary calls of gRPC plus the overhead introduced by PI (`AccessArbitration`) for each singular request seems to be a little strange in such a use-case.

Thanks for your fast answer!
