### ISSUE TITLE
Is there any plan about SONiC + Stratum?

### ISSUE THREAD

**Issue by dingrui37** [stratum/stratum#32]
SONiC could use Stratum as an implementation of SAI ,  is there any plan?

**Comment by pudelkoM** [comment]
Yes there is some talk about integrating with SONiC, but nothing officially announced yet. If you're interested in the discussion you can you the Stratum TST meetings and bring it up.

https://wiki.opennetworking.org/display/COM/Stratum+Wiki+Home+Page
