### ISSUE TITLE
Stratum docker image build fails for bf-sde-9.0.0

### ISSUE THREAD

**Issue by abhilashendurthi** [stratum/stratum#325]
Stratum nightly Jenkins job is failing to build Stratum docker image for bf-sde-9.0.0. Please refer to the build job: https://jenkins.stratumproject.org/blue/organizations/jenkins/stratum-bf-build/detail/stratum-bf-build/561/pipeline

**Comment by pudelkoM** [comment]
Seems like a problem with the SDE. We could update the python version inside the docker image.

**Comment by Yi-Tseng** [comment]
Patch the SDE to use an older version of `jsonschema` python library

**Comment by Yi-Tseng** [comment]
Or we can patch the Dockerfile in the Barefoot directory for now before we move to python3
