### ISSUE TITLE
How to run stratum with the tofino software model?

### ISSUE THREAD

**Issue by li9270** [stratum/stratum#370]
I see that ONLP needs to be disabled when build stratum if running Stratum with the Tofino software model. 
I want to know how to run stratum with the tofino software model?
Is it mean that I can run a simulated barefoot switch, run SDE, and stratum on a PC ?
Is there any tutorial or advice about tofino software model? 
Thanks a lot !

**Comment by wladowaldo** [comment]
I managed to do this a while back - to make bf_switchd go into "MODEL" mode instead of "ASIC", I had to remove the `board-port-map` entry from `stratum/stratum/hal/bin/barefoot/tofino_skip_p4_no_bsp.conf`. Just a hint; hopefully you'll find it useful.

**Comment by li9270** [comment]
Thank for your advise, I remove the board-port-map entry in tofino_skip_p4_no_bsp.conf.  But it can not get port info from a database when stratum push chassis config to switch. It seems that the initialization of database occured when a device add. I have not find when the device was added.

**Comment by bocon13** [comment]
Thanks for the issue! We have added some new scripts and instructions for running Tofino model:

https://github.com/stratum/stratum/blob/master/stratum/hal/bin/barefoot/README.run.md#running-stratum-on-tofino-model

Please let us know if these work for you. If not, you can reopen the issue or start a new one.
