### ISSUE TITLE
Update default port maps to use friendly port ids

### ISSUE THREAD

**Issue by bocon13** [stratum/stratum#379]

**Comment by ux-8** [comment]
> _No description provided._

**Comment by ux-8** [comment]
@ux-8

**Comment by ux-8** [comment]
> > _No description provided._

ux-8

**Comment by ux-8** [comment]
@ux-8

**Comment by ux-8** [comment]
@bocon13

**Comment by ux-8** [comment]
> _No description provided._

**Comment by pudelkoM** [comment]
We want to convert 
```textproto
singleton_ports {
  id: 128
  name: "1/0"
  slot: 1
  port: 1
  speed_bps: 100000000000
  config_params {
    admin_state: ADMIN_STATE_ENABLED
  }
  node: 1
}
```

into this
```textproto
singleton_ports {
  id: 1
  name: "1/0"
  slot: 1
  port: 1
  speed_bps: 100000000000
  config_params {
    admin_state: ADMIN_STATE_ENABLED
  }
  node: 1
}
```

?

**Comment by bocon13** [comment]
@pudelkoM yes, that was the idea -- to use more SDN port numbers that match the physical port numbers.

**Comment by pudelkoM** [comment]
I was thinking about writing a tool to convert these in one go, and deduct the new id from the name string (`"1/0"` -> `id: 1). The tool would reside under `hal/config` with the files and could be used by users to migrate their configs. It would also reorder the fields to match the definition in the proto.

Unless someone has another quick way to convert 15 configs x 32 ports.
