### ISSUE TITLE
Update client arbitration to match P4RT 1.3.0

### ISSUE THREAD

**Issue by bocon13** [stratum/stratum#380]
Our current implementation doesn't quite match the spec:
https://p4.org/p4runtime/spec/v1.2.0/P4Runtime-Spec.html#sec-master-slave-arbitration-and-controller-replication

**Comment by pudelkoM** [comment]
> Election ID should be persisted across reboots in production (can be stored in /dev/null in testing and development)

Is there a section in the spec about this?

**Comment by bocon13** [comment]
Maybe we should add one. @kuujo, was the one that worked on the initial revision and confirmed the need to persist today. Should we propose something to the P4 API WG this Friday?

**Comment by bocon13** [comment]
@pudelkoM Persistence requirement clarification is in the spec here:
https://p4.org/p4runtime/spec/master/P4Runtime-Spec.html#client-arbitration-update

> This invariant must be maintained across in-service software upgrades, and the P4Runtime server must remember the highest election_id after such a restart. However, across a full restart, the election_id must be reset. In fact, a full restart is the only way to reset the election_id.

Given that we don't really support ISSU/NSF/warm reboot, we can probably punt on this issue for now. But we should design it in such a way that makes it easy to persist when we do.
