### ISSUE TITLE
Used experimental function in docker build

### ISSUE THREAD

**Issue by breezestars** [stratum/stratum#382]
**Describe the bug**
When follow readme document to build barefoot stratum, in method 2 will need to execute 
`stratum/hal/bin/barefoot/docker/build-stratum-bf-container.sh`
The process will be fail due using `squash` parameter in docker build command.
The error message is following:
`Error response from daemon: squash is only supported with experimental mode`

**Environment**
OS: Debian 9
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:52 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:23 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

If building from source:
Yes, build by script from repo.

Switch:
Build on other server

**To Reproduce**
1. Install latest Docker-CE
2. Execute `docker buid --squash`

**Expected behavior**
It will remind it is an experimental function

**Additional context**
It can be resolve by add config to docker.
1. Create /etc/docker/daemon.json, and add following content
```
{
        "experimental": true
}
```
2. Restart docker service

**Comment by bocon13** [comment]
fixed in #381
