### ISSUE TITLE
Questions / Issues with new Barefoot build

### ISSUE THREAD

**Issue by bocon13** [stratum/stratum#383]
The Barefoot README and build process was recently overhauled. Leave a comment if you have any concerns or suggestions after the update.

Tracking status of suggestions
- [ ] Dependencies between build options (to build with method 4, need to look at method 3 which then refers to method 2)
- [ ] sde tgz vs tar name

**Comment by breezestars** [comment]
- [ ] There are missing few bf_lib in stratum_bf_deb.deb, e.g. libbf_switchd_lib.so*, libpiall.so*

**Comment by bocon13** [comment]
Closing this issue for now.

We are exploring using Bazel to build containers (#473) which would change the process again. We can rework the build instructions when we revisit that.
