### ISSUE TITLE
P4runtime config indirect meter don't work wedge100bf-32x-r0 with stratum

### ISSUE THREAD

**Issue by xiaohuiluo** [stratum/stratum#398]
**P4runtime config indirect meter don't work on wedge100bf-32x-r0 with stratum(9.2.0-4.14.49-OpenNetworkLinux), but it works fine on stratum-bmv2.**

Hello, I define a indirect meter in p4, use onos 2.1.0 with meter behavior enabled in p4runtime driver to config the indirect meter,  and run stratum with SDE 9.2.0 on wedge100bf-32x-r0.

**I can see log in /var/log/stratum/p4_writes.pb.txt like this:**
```
2020-10-29 09:55:45.018505;1;type: MODIFY entity { meter_entry { meter_id: 335551346 index { index: 136 }  config { cir: 100 cburst: 100 pir: 110 pburst: 110 } } };
2020-10-29 09:55:48.604817;1;type: MODIFY entity { meter_entry { meter_id: 335551346 index { index: 137 }  config { cir: 100 cburst: 100 pir: 110 pburst: 110 } } };
```

I connect two hosts to the switch port 136 and 137(10Gbits/s), use iperf to test bandwidth, and the rate is not limit, so the meter don't work.
```
root@ops-2288H-V5:~# iperf -c 10.10.10.11 -i 1
------------------------------------------------------------
Client connecting to 10.10.10.11, TCP port 5001
TCP window size: 85.0 KByte (default)
------------------------------------------------------------
[  3] local 10.10.10.10 port 37874 connected with 10.10.10.11 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0- 1.0 sec  1.09 GBytes  9.33 Gbits/sec
[  3]  1.0- 2.0 sec  1.09 GBytes  9.39 Gbits/sec
[  3]  2.0- 3.0 sec  1.09 GBytes  9.40 Gbits/sec
[  3]  3.0- 4.0 sec  1.10 GBytes  9.41 Gbits/sec
[  3]  4.0- 5.0 sec  1.09 GBytes  9.37 Gbits/sec
```
**The following is a partial part of the p4 file.**
```
control EgressPipeImpl(inout headers hdr,
                 inout metadata meta,
                 inout standard_metadata_t standard_metadata) {

    meter(MAX_PORTS, MeterType.packets) m_egress_port;
    meter_color m_egress_port_color = METER_COLOR_GREEN;


    action drop() {
        mark_to_drop(standard_metadata);
    }

    apply {
         if (meta.is_packet_out == true) {
	        exit;
         }

         if (standard_metadata.egress_port == CPU_PORT) {
            hdr.packet_in.setValid();
            hdr.packet_in.ingress_port = standard_metadata.ingress_port;
            exit;
         }

         m_egress_port.execute_meter<meter_color>((bit<32>)standard_metadata.egress_port, m_egress_port_color);
         if (m_egress_port_color == METER_COLOR_RED) {
             drop();
         }

    }
}
```
**Whether the indirect meter feature is supported in stratum with SDE 9.2.0 ? How do I make it work?
Thanks  a lot !**

**Comment by Yi-Tseng** [comment]
Hi
Stratum(stratum-bf) doesn't process the P4Runtime write request, it will forward write requests directly to ASIC SDK via PI library. 
I think you can ask this question via [Intel's community forum](https://community.intel.com/t5/Intel-Connectivity-Research/cmp-p/grouphub:connectivity-research-program) or [Barefoot support portal](support.barefootnetworks.com)

**Comment by xiaohuiluo** [comment]
> Hi
> Stratum(stratum-bf) doesn't process the P4Runtime write request, it will forward write requests directly to ASIC SDK via PI library.
> I think you can ask this question via [Intel's community forum](https://community.intel.com/t5/Intel-Connectivity-Research/cmp-p/grouphub:connectivity-research-program) or [Barefoot support portal](support.barefootnetworks.com)

Thank you !
I will ask Intel technical support for help.

**Comment by Yi-Tseng** [comment]
Close this now, feel free to reopen this if you have new questions related to this issue.
