### ISSUE TITLE
Stratum crashes when loading TNA program to Stratum PI

### ISSUE THREAD

**Issue by gjourjon** [stratum/stratum#413]
**Describe the bug**
I have followed the instruction to build stratum for the Wedge and when running the container on the switch I have the following error when pushing the configuration using P4Runtime:

```
E20201108 07:19:33.378788    43 PI-device_mgr.cpp:0] Error in first phase of device update
E20201108 07:19:33.379009    43 bf_switch.cc:108] Return Error: pi_node->PushForwardingPipelineConfig(config) failed with generic::unknown: 
E20201108 07:19:33.379070    43 p4_service.cc:381] generic::unknown: Error without message at stratum/hal/lib/common/p4_service.cc:381
E20201108 07:19:33.379108    43 error_buffer.cc:30] (p4_service.cc:422): Failed to set forwarding pipeline config for node 1: Error without message at stratum/hal/lib/common/p4_service.cc:381
```

**Environment**
Help us understand by giving us some context of your setup.

If building from source:
`bazel version`

Switch:
```bash
cat /etc/onl/platform
x86-64-accton-wedge100bf-32x-r0
uname -a
Linux wedge-5 4.14.49-OpenNetworkLinux #1 SMP Mon Sep 28 23:16:06 UTC 2020 x86_64 GNU/Linux
lsmod
Module                  Size  Used by
bf_kdrv                28672  0
x86_pkg_temp_thermal    16384  0
gpio_ich               16384  0
optoe                  20480  0
```

**To Reproduce**
Just follow the way to build the docker image for barefoot using the latest release. 

**Expected behavior**
I was expecting to be able to load the configuration on the switch using the following command from p4runtime-shell:

`docker run -ti -v /tmp/:/tmp/ p4lang/p4runtime-sh --grpc-addr wedge-5.centie.net.au:28000 --device-id 1 --election-id 0,1 --config /tmp/p4info.pb.txt,/tmp/tofino.bin`
But have the following error:
```
CRITICAL:root:Error when setting config
CRITICAL:root:P4Runtime RPC error (UNKNOWN): Error without message at stratum/hal/lib/common/p4_service.cc:381
```

**Additional context**

**Comment by pudelkoM** [comment]
That error comes from the PI node and means the format or content of the P4 pipeline is not understood by the Tofino SDE. This can have a lot of reasons.

Can you tell us a bit more about the P4 program:

- Which architecture? (bmv2, TNA, etc.)
- Does the p4c compiler version match the SDE version of the Stratum container?
- Any special compiler flags used? (`--p4runtime-force-std-externs`)

**Comment by gjourjon** [comment]
I'm using tna architecture and --p4runtime-force-std-externs is used during the configuration of P4. Here are the details of the configure of p4:
p4-build features recap ......................
P4 Compiler ................... : /home/jou008/bf-sde-9.2.0/install/bin/bf-p4c version:  9.2.0 (SHA: 639d9ec)
P4 Version .................... : p4-16
P4 Path ....................... : PATH/tna_cross_channel/tna_cross_channel.p4
P4 Name ....................... : tna_cross_channel
P4 Prefix ..................... : tna_cross_channel
Compile for Tofino ............ : yes
Compile for Tofino2 ........... : no
Compile for Tofino3 ........... : no
Thrift enabled ................ : no

**Comment by gjourjon** [comment]
I have built the container using the same tar from which I have extracted /home/jou008/bf-sde-9.2.0

**Comment by bocon13** [comment]
Fix is to catch the error and do something other than crash.

Should update the troubleshooting doc

**Comment by shizhoum** [comment]
I also encountered the same problem. Did you solve this problem? If it is solved, please tell me how you solved it. Thank you very much.

**Comment by pudelkoM** [comment]
After some debugging, I found your bug: Don't push the `tofino.bin`directly, you have to pack it like described here:
https://github.com/stratum/stratum/blob/fd40c7bf1bf39a49452e52f5f512468ea0a0ab81/stratum/hal/bin/barefoot/update_config.py#L39-L52

This is unrelated to the `--p4runtime-force-std-externs` flag (which is still needed in any case).

It's safer to use the new protobuf based format with the packer tool: https://github.com/stratum/stratum/blob/master/stratum/hal/bin/barefoot/README.pipeline.md#stratum-bfpipelineconfig-format-and-the-bfpipelinebuilder

Feel free to reopen if the issue persists.
