### ISSUE TITLE
Use glog demangle to improve output of C++ mangled types in gNMI log

### ISSUE THREAD

**Issue by bocon13** [stratum/stratum#453]
Demangle() definition: https://github.com/google/glog/blob/master/src/demangle.h

https://github.com/stratum/stratum/blob/d81b708113c54229245956762036d78af844ba9c/stratum/hal/lib/common/gnmi_events.h#L685

**Comment by pudelkoM** [comment]
glog (and abseil) `Demangle` do not support structs, only function symbols: https://github.com/abseil/abseil-cpp/blob/887d0eee6bab35847253181b32e78ff707010ccd/absl/debugging/internal/demangle.cc#L602

I had some success with `abi::__cxa_demangle` instead:

```
I20210104 21:31:03.259582 29392 gnmi_events.h:708] Handling stratum::hal::ConfigHasBeenPushedEvent
I20210104 21:31:04.620774 29449 gnmi_events.h:708] Handling stratum::hal::PortOperStateChangedEvent
```
