### ISSUE TITLE
Support for digests and idle timeout notifications on tofino?

### ISSUE THREAD

**Issue by henli070** [stratum/stratum#482]
Hi, is it possible to get digests and idle timeout notifications through Stratum when running on tofino?
From what i can tell it seems like this is not currently supported, but i could be wrong.
Thanks!

**Comment by pudelkoM** [comment]
I think technically yes. Whatever the SDE exposes, we can translate to the P4RT equivalent and publish.

I'm not aware of any immediate need (and therefore effort) from ONF side, but we're happy to collaborate on a solution.

**Comment by stolsma** [comment]
@pudelkoM I was trying to use Digest entry (and Digest:pack in my p4 program) on Stratum-bfrt and I got the impression (see below) that DigestEntry isn't implemented yet by #536 voor stratum_bfrt. Am I right??

Is it implemented for any other target? If so, what needs to be done to get it implemented for stratum_bfrt?

https://github.com/stratum/stratum/blob/8563024d66d53b3d2a3c7d6c88afea0745ac8314/stratum/hal/lib/barefoot/bfrt_node.cc#L180-L189

**Comment by pudelkoM** [comment]
> DigestEntry isn't implemented yet by #536 voor stratum_bfrt

correct. bfrt does not support `DigestEntry` yet.

> Is it implemented for any other target?

Stratum-bf supports it, through PI node.

> If so, what needs to be done to get it implemented for stratum_bfrt?

Since there is a notion of caching and acknowledgements, this is a little more involved that just passing through a few function calls to the SDE. I think the PI code would be a good starting point.

**Comment by stolsma** [comment]
> correct. bfrt does not support `DigestEntry` yet.
>
> Stratum-bf supports it, through PI node.

Ah, of course.. Will try that one, with the correct tna flag for p4c...

> > If so, what needs to be done to get it implemented for stratum_bfrt?
> 
> Since there is a notion of caching and acknowledgements, this is a little more involved that just passing through a few function calls to the SDE. I think the PI code would be a good starting point.

Thanks for your quick response! Unfortunately I'm not so proficient in C so I think it's not a good idea that I try to code that implementation 😔 Hopefully there will be another hero who will implement this...😉
