### ISSUE TITLE
stratum_bmv2 does not send P4Runtime DigestList via StreamChannel

### ISSUE THREAD

**Issue by ccascone** [stratum/stratum#528]
Even if bmv2 and PI support P4Runtime digests, `StreamMessageResponse.DigestList` messages do not come out of `stratum_bmv2` when they should. I believe this is happening because we don't have a "digest channel" as we do for packet-ins in the p4_service/switch_interface.

**Comment by daniele-moro** [comment]
Was this solved? I'm still not able to use digest in `stratum_bmv2` (i.e., in UP4 STCs).
