### ISSUE TITLE
Stratum prints error about reading counters that doesn't support by the table

### ISSUE THREAD

**Issue by Yi-Tseng** [stratum/stratum#668]
**Describe the bug**
After update to SDE 9.5.0, and use the ONOS to control it(with TOST) Stratum start showing the following logs:

```
2021-05-04 02:06:52.818523 BF_BFRT ERROR - getDataField:1812 Data field name $COUNTER_SPEC_BYTES actionID 28485346 not found
2021-05-04 02:06:52.818574 BF_BFRT ERROR - getDataField:1812 Data field name $COUNTER_SPEC_PKTS actionID 28485346 not found
```

**Environment**
Use container image: `stratumproject/stratum-bfrt:9.5.0` (build with latest main 14c99349)

Switch: WedgeBF-32QS with ONL 4.14.49

**To Reproduce**

Load fabric-tna fabric-int pipeline with SDE 9.5.0 p4c output by using p4runtime-shell and run following:

```
te = table_entry['FabricIngress.forwarding.routing_v4']()
te.is_default = True
te.read(lambda x: print(x))
```

**Expected behavior**

 - Stratum should not show the error in the description above

**Comment by Yi-Tseng** [comment]
After checking the action ID from p4info, it seems that we are trying to query counters from tables that don't support counter.

**Comment by Yi-Tseng** [comment]
I believed [printing the error is the new feature from SDE 9.5.0 since it didn't print the error when using SDE 9.3.1
Would be nice to check if the table supports the counter before reading the counter.

Ref: https://github.com/stratum/stratum/blob/main/stratum/hal/lib/barefoot/bf_sde_wrapper.cc#L911-L929

**Comment by pudelkoM** [comment]
Yeah, can confirm the new log message.

I think our model of probe-and-recover when dealing with the SDE is not the correct one. It expects that you only make calls which are valid.
