### ISSUE TITLE
Unable to add reviewers to PRs

### ISSUE THREAD

**Issue by ccascone** [stratum/stratum#69]
I don't know if I'm the only one seeing this issue, but when submitting a PR I cannot request reviews as the Github button/input form on the right is not shown/clickable. Perhaps, we need to update permissions on GitHub to allow anyone to request reviews? Otherwise, I think we should change this line in the contributor's guidelines:

> Request review. You can add anyone you think is helpful, but only Collaborators and above can give final approval. 

Ping @pudelkoM

**Comment by ccascone** [comment]
Here's an animated GIF showing what it looks like from a PR I submitted earlier today ![Dec-16-2019 18-10-19](https://user-images.githubusercontent.com/3025473/70958893-6cda0280-202f-11ea-9a58-47004bcc8092.gif)

**Comment by pudelkoM** [comment]
Seems like GitHub does not actually allow review requests from PR authors:

> Note: Pull request authors can't request reviews unless they are either a repository owner or collaborator with write access to the repository.

**Comment by pudelkoM** [comment]
Can you comment on code changes in a PR? I'd use this as a workaround for non-contributors in this case.
