### ISSUE TITLE
File x86-64-netberg-aurora-750-r0/port_map.json has syntax error

### ISSUE THREAD

**Issue by naradahess** [stratum/stratum#744]
File stratum/hal/config/x86-64-netberg-aurora-750-r0/port_map.json has a JSON syntax error on line 243:
    "rx_pn_swap": ,
The value is missing before the comma. Not sure what the correct value should be, so cannot submit the fix myself.

NOTE: stratum/hal/config/x86-64-netberg-aurora-710-r0/port_map.json also has the following issues:
- Missing the terminal comma on line 554.
- Missing a value on line 618. The value for "tx_lane" should be 1.

Found using a JSON validation tool. Does not break the build. But these should be fixed.

**Comment by pudelkoM** [comment]
Thanks for the report. Fixed in #745
