### ISSUE TITLE
Need cmake and library realize

### ISSUE THREAD

**Issue by lxlmummy** [stratum/stratum#79]
I am a newer interesting in stratum, I have tried the stratum p4runtime function，build and run in my barefoot device. so，I have two suggests as follows,
    Frist my device os building system is based on buildroot， I hope you can offer a common cmake compile method，not now bazel only.
    Second，all the stratum code build as only a binary bin，but some users may have their own grpc server realize，they hope stratum project supply  APIs ，not only a binay binary bin。So, in future, I hope some librarys which supply API for the p4runtime.

**Comment by pudelkoM** [comment]
We have over 280 source files and at least 3 binary targets. Adding a second build system would be a significant effort for very little immediate gain.

I'm not sure I understand your second point. Stratum is not binary only. In fact, all logic is contained in classes and structured in a reusable format. If you just want shared libraries, look into the `bazel-bin` directory after a full bazel build. Together with the header files, these could be used by different projects.

**Comment by pudelkoM** [comment]
Closing this now.
If you can present a compelling use case and PR, feel free to reopen.
