### ISSUE TITLE
Update BF SDE Build Scripts for 9.6.0

### ISSUE THREAD

**Issue by bocon13** [stratum/stratum#795]
SDE 9.6.0 has changed the build process. p4studio_build.py is now p4studio.

We need to update our build scripts to generate the appropriate BF SDE install packages.

- [ ] Rework the SDE build script; bf-sde-9.6.0-install.tgz was built by hand
- [ ] Update how we build BSP
- [ ] Update how we build kernel modules
- [ ] Add libcli.so to tofino-model container (requires SDE build)

**Comment by Yi-Tseng** [comment]
@bocon13 should we close this one? (skip 9.6.0)

**Comment by bocon13** [comment]
Yes, let's close this as we are skipping 9.6.0

**Comment by pudelkoM** [comment]
I'd expect it to be similar to 9.7.0, so should we ever need it we go from there.
