### ISSUE TITLE
When I start stratum by stratum/hal/bin/barefoot/docker/start-stratum-container.sh，It will report error info，Should I ignore it or fix it

### ISSUE THREAD

**Issue by linhil** [stratum/stratum#964]
When I start stratum by stratum/hal/bin/barefoot/docker/start-stratum-container.sh，how should I follow up，fix it or ignore it？I ran it on P4 hareware switch.
Could someone help me to solve this problem？ Thank you！

```
> I20220512 10:35:20.561856     1 config_monitoring_service.cc:94] Pushing the saved chassis config read from /etc/stratum/x86-64-accton-wedge100bf-32x-r0/chassis_config.pb.txt...
> E20220512 10:35:20.572890     1 bf_chassis_manager.cc:414] StratumErrorSpace::**ERR_INVALID_PARAM**: Unsupported platform: PLT_P4_SOFT_SWITCH
> E20220512 10:35:20.573276     1 bf_chassis_manager.cc:701] StratumErrorSpace::**ERR_NOT_INITIALIZED: Not initialized!**
> E20220512 10:35:20.573295     1 bf_switch.cc:50] **Return Error: VerifyChassisConfig(config) failed with StratumErrorSpace::ERR_INVALID_PARAM: Unsupported platform: PLT_P4_SOFT_SWITCH.**
> E20220512 10:35:20.573313     1 **error_buffer.cc:30] (config_monitoring_service.cc:124): Pushing saved chassis config failed: Unsupported platform: PLT_P4_SOFT_SWITCH.**
> E20220512 10:35:20.573354     1 hal.cc:136] **Return Error: config_monitoring_service_->Setup(FLAGS_warmboot) failed with StratumErrorSpace::ERR_INVALID_PARAM: Unsupported platform: PLT_P4_SOFT_SWITCH.**
> E20220512 10:35:20.573369     1 main.cc:170] **Error when setting up Stratum HAL (but we will continue running): Unsupported platform: PLT_P4_SOFT_SWITCH.**

```

**Comment by linhil** [comment]
I changed the chassis config file, it has errors 

E20220512 10:59:43.383975     1 bf_chassis_manager.cc:476] StratumErrorSpace::ERR_INVALID_PARAM: '!singleton_port_keys.count(singleton_port_key)' is false. The (slot, port, channel) tuple for SingletonPort (node_id: 1, port_id: 132, slot: 1, port: 2, speed: 10G) was already recorded for another SingletonPort in the config.
E20220512 10:59:43.384356     1 bf_chassis_manager.cc:701] StratumErrorSpace::ERR_NOT_INITIALIZED: Not initialized!
E20220512 10:59:43.384380     1 bf_switch.cc:50] Return Error: VerifyChassisConfig(config) failed with StratumErrorSpace::ERR_INVALID_PARAM: '!singleton_port_keys.count(singleton_port_key)' is false. The (slot, port, channel) tuple for SingletonPort (node_id: 1, port_id: 132, slot: 1, port: 2, speed: 10G) was already recorded for another SingletonPort in the config.

**Comment by Dscano** [comment]
Hi,

I think that you have to add additional flags to `start-stratum-container.sh` script.  Such as CHASSIS_CONFIG    
SDE_VERSION, PLATFORM .
Based on your platform you can find here the correctchassis config file https://github.com/stratum/stratum/tree/main/stratum/hal/config

**Comment by linhil** [comment]
> 

I changed to correct chassis config file https://github.com/stratum/stratum/tree/main/stratum/hal/config, it runs like 

```
I20220512 12:05:11.057706     1 config_monitoring_service.cc:94] Pushing the saved chassis config read from /etc/stratum/x86-64-accton-wedge100bf-32x-r0/chassis_config.pb.txt...
E20220512 12:05:11.070566     1 bf_chassis_manager.cc:701] StratumErrorSpace::ERR_NOT_INITIALIZED: Not initialized!
I20220512 12:05:11.070962     1 bf_switch.cc:100] Chassis config verified successfully.
I20220512 12:05:11.072755     1 onlp_wrapper.cc:99] Initializing ONLP.
E20220512 12:05:11.074144     1 onlp_wrapper.cc:91] StratumErrorSpace::ERR_INVALID_PARAM: 'dl_err == nullptr' is false. Failed to load symbol onlp_sw_init: /lib/x86_64-linux-gnu/libonlp.so: undefined symbol: onlp_sw_init
E20220512 12:05:11.074177     1 onlp_wrapper.cc:111] Return Error: LoadSymbol<decltype(onlp_functions_.onlp_sw_init)>(onlp_lib_handle_, "onlp_sw_init") at stratum/hal/lib/phal/onlp/onlp_wrapper.cc:111
E20220512 12:05:11.074189     1 onlp_wrapper.cc:76] OnlpWrapper::Init() failed: StratumErrorSpace::ERR_INVALID_PARAM: 'dl_err == nullptr' is false. Failed to load symbol onlp_sw_init: /lib/x86_64-linux-gnu/libonlp.so: undefined symbol: onlp_sw_init
I20220512 12:05:11.074206     1 onlp_wrapper.cc:60] Deinitializing ONLP.
*** Aborted at 1652357111 (unix time) try "date -d @1652357111" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x0) received by PID 1 (TID 0x7fddf8229800) from PID 0; stack trace: ***
    @     0x7fddc39c80e0 (unknown)
    @                0x0 (unknown)

```

**Comment by Dscano** [comment]
Do you have installed Open Network Linux as NOS? witch version? If you don't have it as NOS you should run stratum with `-enable_onlp=false `

**Comment by linhil** [comment]
> Do you have installed Open Network Linux as NOS? witch version? If you don't have it as NOS you should run stratum with `-enable_onlp=false `

I've installed ONL  4.14 and 4.19, but use the branch 2020-12 for sde 9.1.0 and 9.2.0, and tried for a long time.

**Comment by pudelkoM** [comment]
`2020-12` is less of a branch than a snapshot release. There are no bugfixes or development happening on old releases. Commits go to `main` and new releases are cut from there. Therefore I'd suggest you updated to a newer version, both Stratum and the SDE, if possible. Support for `9.2.0` has been removed in 7de325cdfe2340154e6babaae6bb57e45e383fb1.

Thanks @Dscano for helping out here!

**Comment by linhil** [comment]
> `2020-12` is less of a branch than a snapshot release or tag. There are no bugfixes or development happening on old releases. Commits go to `main` and new releases are cut from there. Therefore I'd suggest you update to a newer version, both Stratum and the SDE, if possible. Support for `9.2.0` has been removed in [4df8d28](https://github.com/stratum/stratum/commit/4df8d288a4e958a74b661bda45cd997da575488a). Current list of supported SDEs can be found here: https://github.com/stratum/stratum/blob/main/stratum/hal/bin/barefoot/README.build.md#supported-sde-versions
> 
> Thanks @Dscano for helping out here!

I change to sde-9.5.2, but when I type  `stratum/hal/bin/barefoot/docker/build-stratum-bf-container.sh` , It returns 
`+ docker run --rm -v /root:/bf-tar -e SDE_INSTALL_TAR=/bf-tar/bf-sde-9.5.2-install.tgz -it -v /root/stratum:/stratum -v /root/stratum:/output -w /stratum --entrypoint bash stratumproject/build:build -c 'bazel build //stratum/hal/bin/barefoot:stratum_bfrt_deb                --jobs 4 &&      cp -f /stratum/bazel-bin/stratum/hal/bin/barefoot/stratum_bfrt_deb.deb /output/ &&      cp -f $(readlink -f /stratum/bazel-bin/stratum/hal/bin/barefoot/stratum_bfrt_deb.deb) /output/'
Starting local Bazel server and connecting to it...
DEBUG: Rule 'com_github_nelhage_rules_boost' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1576879360 -0800"
DEBUG: Repository com_github_nelhage_rules_boost instantiated at:
  /stratum/WORKSPACE:39:13: in <toplevel>
  /stratum/bazel/deps.bzl:230:23: in stratum_deps
Repository rule git_repository defined at:
  /root/.cache/bazel/_bazel_root/1b07b1db06ec9ee22c71eac6f0bd4549/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
DEBUG: /stratum/stratum/hal/lib/barefoot/barefoot.bzl:24:10: SDE with BSP: True.
DEBUG: /stratum/stratum/hal/lib/barefoot/barefoot.bzl:31:10: Detected SDE version: 9.5.1.
ERROR: /stratum/stratum/hal/lib/barefoot/BUILD:195:19: Configurable attribute "defines" doesn't match this configuration: Unsupported SDE version
INFO: Repository com_github_gflags_gflags instantiated at:
  /stratum/WORKSPACE:39:13: in <toplevel>
  /stratum/bazel/deps.bzl:197:21: in stratum_deps
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/1b07b1db06ec9ee22c71eac6f0bd4549/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Repository com_github_p4lang_p4runtime instantiated at:
  /stratum/WORKSPACE:39:13: in <toplevel>
  /stratum/bazel/deps.bzl:67:21: in stratum_deps
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/1b07b1db06ec9ee22c71eac6f0bd4549/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Repository build_bazel_rules_swift instantiated at:
  /stratum/WORKSPACE:48:16: in <toplevel>
  /root/.cache/bazel/_bazel_root/1b07b1db06ec9ee22c71eac6f0bd4549/external/com_github_grpc_grpc/bazel/grpc_extra_deps.bzl:52:29: in grpc_extra_deps
  /root/.cache/bazel/_bazel_root/1b07b1db06ec9ee22c71eac6f0bd4549/external/build_bazel_rules_apple/apple/repositories.bzl:117:11: in apple_rules_dependencies
  /root/.cache/bazel/_bazel_root/1b07b1db06ec9ee22c71eac6f0bd4549/external/build_bazel_rules_apple/apple/repositories.bzl:84:14: in _maybe
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/1b07b1db06ec9ee22c71eac6f0bd4549/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: Analysis of target '//stratum/hal/bin/barefoot:stratum_bfrt_deb' failed; build aborted: /stratum/stratum/hal/lib/barefoot/BUILD:195:19: Configurable attribute "defines" doesn't match this configuration: Unsupported SDE version
INFO: Elapsed time: 59.268s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (54 packages loaded, 616 targets configured)
    currently loading: @com_google_googleapis//google/rpc ... (2 packages)`
