### ISSUE TITLE
 tar ball bf-sde-9.5.2-install.tgz VERION issues

### ISSUE THREAD

**Issue by linhil** [stratum/stratum#966]
[Method2.step2 Build Stratum using Docker](https://github.com/stratum/stratum/blob/main/stratum/hal/bin/barefoot/README.build.md#step-2-build-stratum-using-docker)

I change to sde-9.5.2 and stratum-main branch, but when I type `stratum/hal/bin/barefoot/docker/build-stratum-bf-container.sh` , I chose the correct sde-9.5.2, it has errors like `/stratum/stratum/hal/lib/barefoot/BUILD:195:19: Configurable attribute "defines" doesn't match this configuration: Unsupported SDE version`, I find in `bf-sde-9.5.2-install.tgz` I created, the `.share/VERSION is 9.5.1` I don't know why

**Comment by linhil** [comment]
it returns 

`2022-05-14 07:15:21,302 - p4studio_build - WARNING -           Profile stratum_profile.yaml is not of current SDE. Please use profile of current SDE version [9.5.2] to avoid any discrepancies or failures
`

**Comment by pudelkoM** [comment]
If the `VERSION` files shows `9.5.1` then I suspect this is not the correct SDE version. Only `9.5.2` is supported.
