### ISSUE TITLE
Connect ONOS with Stratum

### ISSUE THREAD

**Issue by tisasi001** [stratum/stratum#972]
**Describe the bug**
I installed stratum in my tofino switch with SDE version 9.5.0, and it runned without errors. At the same tame I installed ONOS version
2.7.0 with the fabric-tna pipeconf. When running stratum now with ONOS installed in another machine (ip4=10.98.1.42), it appears that Stratum detected a controller, but I get some errors after that. At the end I send you the error I get by stratum.

**Environment**
Here I send you some information about my setup:

My switch is a Tofino switch, x86-64-stordis-bf2556x-1t-r0.

admin-p4-1@ubuntu-p4-1:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

uname -r
5.4.0-40-generic

**Main error**
This is the main error I get:

I20220525 11:38:08.138631 24092 p4_service.cc:796] Controller (connection_id: 1, election_id: 180, uri: ipv4:10.98.1.42:37278) is connected as MASTER for node (aka device) with ID 1.
I20220525 11:38:08.255345 24096 bfrt_switch.cc:277] P4-based forwarding pipeline config verified successfully for node with ID 1.
bf_switchd: starting warm init for dev_id 0 mode 1 serdes_upgrade 0
Skip diag lib deinit
**2022-05-25 11:38:08.378417 BF_PIPE ERROR - Error Invalid arguments parsing compiler version string "9.7.0 (da5115f)" for dev 0 profile 0, program name fabric_tna pipeline name pipe config file /var/run/stratum/bfrt_config/fabric_tna/pipe/tofino.bin**
2022-05-25 11:38:08.378516 BF_PIPE ERROR - pipe_mgr_ctx_json_parse:6793: Failed to parse version from ContextJSON
2022-05-25 11:38:08.387003 BF_PIPE ERROR - pipe_mgr_rmt_import : Error in parsing the context jSON file
2022-05-25 11:38:08.387049 BF_PIPE ERROR - pipe_mgr_add_rmt_device: failed to import rmt config
2022-05-25 11:38:08.387084 BF_PIPE ERROR - pipe_mgr_add_device: failed to instantiate device No system resources 2
2022-05-25 11:38:08.387120 BF_DVM ERROR - Device add handling failed for dev 0, sts No system resources (2), Client pipe-mgr
2022-05-25 11:38:08.387156 BF_DVM ERROR - Device add failed for dev 0, sts No system resources (2)
2022-05-25 11:38:08.387194 BF_TM ERROR - TM: tm_remove_device called without valid tm_ctx for device 0
2022-05-25 11:38:08.387752 BF_PIPE ERROR - pipe_mgr_remove_device: failed to de-instantiate device 0
ERROR: bf_device_add failed(2) for dev_id 0
ERROR: bf_switchd_device_add failed(2) for dev_id 0
E20220525 11:38:08.388741 24096 bf_sde_wrapper.cc:1840] StratumErrorSpace::ERR_NO_RESOURCE: 'bf_pal_device_add(device, &device_profile)' failed with error message: No system resources.
E20220525 11:38:08.389117 24096 bfrt_node.cc:138] Return Error: bf_sde_interface_->AddDevice(device_id_, bfrt_config_) failed with StratumErrorSpace::ERR_NO_RESOURCE: 'bf_pal_device_add(device, &device_profile)' failed with error message: No system resources.
E20220525 11:38:08.389154 24096 bfrt_switch.cc:75] Return Error: bfrt_node->PushForwardingPipelineConfig(config) failed with StratumErrorSpace::ERR_NO_RESOURCE: 'bf_pal_device_add(device, &device_profile)' failed with error message: No system resources.
E20220525 11:38:08.389209 24096 error_buffer.cc:29] (p4_service.cc:470): Failed to set forwarding pipeline config for node 1: 'bf_pal_device_add(device, &device_profile)' failed with error message: No system resources.

**Comment by Dscano** [comment]
Hi,

I think that you are trying to run the last version of fabric-tna. This "application" is developed for sde 9.7.0.  While you aree installed 9.5.0. So you have issue from the point of view of versionioning. You should try to compile fabric-ta with sde 9.5.0 but i thint that the app could not work properly.

**Comment by tisasi001** [comment]
Hello,
Thank you for answering. So if fabric-tna doesn't work with sde 9.5.0, should I try to install stratum with version 9.7.0 so both fabric-tna and stratum have the same version?

**Comment by Dscano** [comment]
Hi,

here you can find the fabric-tna repository https://github.com/stratum/fabric-tna,  in the requirements they say SDE 9.7.0 https://github.com/stratum/fabric-tna#requirements. Tha last release of stratum work with SDE 9.7.0 and SDE 9.5.0 https://github.com/stratum/stratum/releases/tag/2022-03-18. So you should compile the fabric-tna with the same SDE version installed on the switch

**Comment by Dscano** [comment]
Hi,

I runned stratum with this flags:

`sudo stratum_bfrt -bf_sde_install /home/tofino/SDE-9.7.0/bf-sde-9.7.0/install -bf_switchd_cfg /usr/share/stratum/tofino_skip_p4.conf  -bf_switchd_background=false -enable_onlp=false -chassis_config_file ./chassis_config.pb.txt -experimental_enable_p4runtime_translation  -incompatible_enable_bfrt_legacy_bytestring_responses`

Some of them are specified here https://github.com/stratum/fabric-tna#2---start-stratum-on-your-switch and I think that are not enabled by default. I think that you shuld try to run stratum with those flags.

Did you change the P4 code of fabric-tna.p4?

**Comment by Dscano** [comment]
Hi, seems that it's working. If evething is woking well you should see the device with a "geen chek" in the devices tab in the GUI.
You should also see the flow rules added in the device flow table.

**Comment by tisasi001** [comment]
Yes, it appears with a green check in the GUI, thank you so much for your help!
